### ISSUE TITLE
Nullpointer when switching Server(world?) using Bungeecord

### ISSUE THREAD

**Issue by tr7zw** [DragonetMC/DragonProxy#117]
The new entity update seems to have a bug with switching servers.
`java.lang.NullPointerException
        at org.dragonet.proxy.network.cache.EntityCache.getByRemoteEID(EntityCache.java:70)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:33)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:23)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:125)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:90)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:335)
        at java.lang.Thread.run(Thread.java:748)`
Crashes win10 client and the dragonproxy.

**Comment by tr7zw** [comment]
Ok never mind was fixed ~2 hours after I compiled my version 😅
