### ISSUE TITLE
ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by yoft** [DragonetMC/DragonProxy#124]
Exception being thrown from this line:
https://github.com/DragonetMC/DragonProxy/blob/cab4c6462de796b8ef1eacd429b8e76711d598bf/proxy/src/main/java/org/dragonet/proxy/network/translator/pc/PCMultiChunkDataPacketTranslator.java#L82

Due to:
https://github.com/DragonetMC/DragonProxy/blob/cab4c6462de796b8ef1eacd429b8e76711d598bf/proxy/src/main/java/org/dragonet/proxy/protocol/type/chunk/Section.java#L23

I tried resizing it but then extra blocks started appearing...

**Comment by HoverEpic** [comment]
You can comment lines 82 & 83, it's an error, blocks meta are not functionnal. I'm contacting @Creeperface01 to ask him if he got it working.

**Comment by DefinitlyEvil** [comment]
gg

**Comment by DefinitlyEvil** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: 2048
        at org.dragonet.proxy.network.translator.pc.PCMultiChunkDataPacketTranslator.processChunkSection(PCMultiChunkDataPacketTranslator.java:81)
        at org.dragonet.proxy.network.translator.pc.PCMultiChunkDataPacketTranslator.lambda$translate$0(PCMultiChunkDataPacketTranslator.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Creeperface01** [comment]
I'll try to fix it

**Comment by HoverEpic** [comment]
Ok thanks

**Comment by HoverEpic** [comment]
Fixed https://github.com/DragonetMC/DragonProxy/commit/409b953aca4d372128b13623c618cc5458a3f336

Some blocks are not rendered as they do, but the hard part of the translator is ok.
