### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by TheIntelloBox** [DragonetMC/DragonProxy#140]
[16:50:12] [Server thread/ERROR]: Could not load 'plugins/dragonproxy-0.3.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by krusic22** [comment]
It's not a plugin. It's a standalone jar. Just run is like "java -jar dragonproxy.jar"

**Comment by TheIntelloBox** [comment]
So I can't put it on my server ?

**Comment by krusic22** [comment]
As a plugin. No.

**Comment by DefinitlyEvil** [comment]
you can put it into a server if you can upload custom server jars.
