### ISSUE TITLE
i cant join mcpe server.(mcpe 0.14.2)

### ISSUE THREAD

**Issue by haniokasai** [DragonetMC/DragonProxy#145]
i tried to join the pocketmine server through dragonproxy,but error occured.
 
23:34:12 [INFO] Binding on 0.0.0.0:191 ... 
23:34:12 [INFO] The proxy has started! 
23:34:44 [INFO] Player hanicraft[/118.241.74.52:19132] connected! 
23:34:44 [WARNING] java.lang.NullPointerException
23:34:44 [WARNING] 	at org.dragonet.raknet.client.Connection.handleEncapsulatedPacket(Connection.java:361)
23:34:44 [WARNING] 	at org.dragonet.raknet.client.Connection.handlePacket(Connection.java:512)
23:34:44 [WARNING] 	at org.dragonet.raknet.client.ConnectionManager.receivePacket(ConnectionManager.java:158)
23:34:44 [WARNING] 	at org.dragonet.raknet.client.ConnectionManager.tickProcessor(ConnectionManager.java:119)
23:34:44 [WARNING] 	at org.dragonet.raknet.client.ConnectionManager.run(ConnectionManager.java:107)
23:34:44 [WARNING] 	at org.dragonet.raknet.client.ConnectionManager.<init>(ConnectionManager.java:70)
23:34:44 [WARNING] 	at org.dragonet.raknet.client.JRakLibClient.run(JRakLibClient.java:218)
23:35:39 [INFO] Client hanicraft[/118.241.74.52:19132] disconnected! Reason: Client disconnect
>

**Comment by CubeFromSpace** [comment]
It looks like a problem with Raknet.

**Comment by TheDiamondYT1** [comment]
Since when do we still use JRakLib??!!

**Comment by TheDiamondYT1** [comment]
Could you please try downloading commit. 27615db?

**Comment by TheDiamondYT1** [comment]
This is just before we updated Raknet.

**Comment by TheDiamondYT1** [comment]
https://circleci.com/gh/DragonetMC/DragonProxy/300

**Comment by haniokasai** [comment]
i used latest dragonproxy...

**Comment by TheDiamondYT1** [comment]
And I just told you not to because @DefinitlyEvil changed some code...

**Comment by Creeperface01** [comment]
there is a probloem with decoding encapsulated packet but idk where

**Comment by kabluinc** [comment]
apparently this is a link to the 0.14.2 working version https://circleci.com/gh/DragonetMC/DragonProxy/300
but I cant find any download link or button to actually download it

**Comment by CubeFromSpace** [comment]
@Creeperface01 it's located at:
https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/raknet/client/Connection.java
and
https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/raknet/client/ConnectionManager.java
these are links to the files.

**Comment by DefinitlyEvil** [comment]
Thanks for testing and I will track this exception for its fix.
