### ISSUE TITLE
Cause PE client crash 

### ISSUE THREAD

**Issue by Mime-AL** [DragonetMC/DragonProxy#151]
English is my second language.Overlooking my poor English.
Server version:PaperSpigot 1.12 with ViaVersion
Dragon Proxy version:3.0.0
Client version:minecraft windows 10 Edition 1.2.7
Client would be crash when I connect to DragonProxy server without any report.
Here is Log:
PING /112.---.---.80:64859
PING /112.---.---.80:64859
PING /112.---.---.80:64859
PING /112.---.---.80:64859
CLIENT CONNECT
CLIENT PROTOCOL = 160
[23:26:27] [INFO] Player AqoursKyaronBE[/112.---.---.80:54255] connected! 
[23:26:27] [INFO] Bridge established for player AqoursKyaronBE[/112.---.---.80:54255]! 
SPAWNED! 
Session exception: Session timeout
net.marfgamer.jraknet.session.TimeoutException: Session timeout
        at net.marfgamer.jraknet.session.RakNetSession.update(RakNetSession.java:865)
        at net.marfgamer.jraknet.server.RakNetServer.start(RakNetServer.java:803)
        at net.marfgamer.jraknet.server.RakNetServer$1.run(RakNetServer.java:837)
CLIENT DISCONNECT
[23:26:27] [INFO] Client AqoursKyaronBE[/112.---.---.80:54255] disconnected! Reason: Client disconnect

**Comment by DefinitlyEvil** [comment]
pls try to use latest dev build on TravisCI.

**Comment by HoverEpic** [comment]
I think I'll put the commit hash in version printed in the log.

**Comment by lukeeey** [comment]
@DefinitelyEvil Travis doesnt create artifacts, circle does

**Comment by DefinitlyEvil** [comment]
Already released 0.3.1 as fix

**Comment by DefinitlyEvil** [comment]
@fjsmnikola still crashing?

**Comment by Mime-AL** [comment]
@DefinitlyEvil No，it worked well
