### ISSUE TITLE
entity meta translation errors

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#154]
```
java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Boolean
        at org.dragonet.proxy.network.translator.EntityMetaTranslator.translateToPE(EntityMetaTranslator.java:237)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:49)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:32)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:134)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:335)
        at java.lang.Thread.run(Thread.java:745)
java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Boolean
        at org.dragonet.proxy.network.translator.EntityMetaTranslator.translateToPE(EntityMetaTranslator.java:237)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:49)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:32)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:134)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:335)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by HoverEpic** [comment]
Seems the bat don't want to hang ^^
https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/network/translator/EntityMetaTranslator.java#L237
I've put a bad value.

**Comment by DefinitlyEvil** [comment]
nvm I temporarely commented that out

**Comment by DefinitlyEvil** [comment]
btw do not use `packets.toArray(new Packet[]{})` in translators, just return null is okay.

**Comment by DefinitlyEvil** [comment]
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float
        at org.dragonet.proxy.network.translator.EntityMetaTranslator.translateToPE(EntityMetaTranslator.java:153)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:78)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:34)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:139)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:335)
        at java.lang.Thread.run(Thread.java:745)
spawning at Vector3F (-432.31, 27.62, -1996.01)
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float
        at org.dragonet.proxy.network.translator.EntityMetaTranslator.translateToPE(EntityMetaTranslator.java:153)
        at org.dragonet.proxy.network.translator.pc.PCPlayerPositionRotationPacketTranslator.translate(PCPlayerPositionRotationPacketTranslator.java:245)
        at org.dragonet.proxy.network.translator.pc.PCPlayerPositionRotationPacketTranslator.translate(PCPlayerPositionRotationPacketTranslator.java:48)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:139)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:335)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by DefinitlyEvil** [comment]
I will comment out that translator for now.

**Comment by HoverEpic** [comment]
Ok I'll fix that on the next pass on entities.

**Comment by DefinitlyEvil** [comment]
xD thx

**Comment by HoverEpic** [comment]
Should be ok.
