### ISSUE TITLE
wip window items click error (gui windows)

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#155]
```
TYPE_NORMAL
java.lang.ArrayIndexOutOfBoundsException: 2
        at org.dragonet.proxy.network.translator.pe.PEInventoryTransactionPacketTranslator.translate(PEInventoryTransactionPacketTranslator.java:71)
        at org.dragonet.proxy.network.translator.pe.PEInventoryTransactionPacketTranslator.translate(PEInventoryTransactionPacketTranslator.java:42)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPC(PacketTranslatorRegister.java:156)
        at org.dragonet.proxy.network.PEPacketProcessor.handlePacket(PEPacketProcessor.java:104)
        at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.java:62)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by DefinitlyEvil** [comment]
and you should remove `translateSlotToPE x` thing, it lags the proxy.

**Comment by DefinitlyEvil** [comment]
```
TYPE_NORMAL
interact in player inventory (inventory)
java.lang.NullPointerException
        at org.dragonet.proxy.network.translator.pe.PEInventoryTransactionPacketTranslator.translate(PEInventoryTransactionPacketTranslator.java:90)
        at org.dragonet.proxy.network.translator.pe.PEInventoryTransactionPacketTranslator.translate(PEInventoryTransactionPacketTranslator.java:45)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPC(PacketTranslatorRegister.java:156)
        at org.dragonet.proxy.network.PEPacketProcessor.handlePacket(PEPacketProcessor.java:104)
        at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.java:62)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by HoverEpic** [comment]
should be ok
