### ISSUE TITLE
Shutdown errors is this normal?

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#158]
```
stop
[14:39:53] [INFO] Shutting down DragonProxy...
Thread exception: sleep interrupted
net.marfgamer.jraknet.RakNetException: sleep interrupted
        at net.marfgamer.jraknet.server.RakNetServer.start(RakNetServer.java:819)
        at net.marfgamer.jraknet.server.RakNetServer$1.run(RakNetServer.java:837)
net.marfgamer.jraknet.RakNetException: sleep interrupted
        at net.marfgamer.jraknet.server.RakNetServer.start(RakNetServer.java:819)
        at net.marfgamer.jraknet.server.RakNetServer$1.run(RakNetServer.java:837)
Goodbye!
```

**Comment by TheMasterBlaster** [comment]
Iv had a few of these and it doesn't seem to hurt anything, Ill guess its not meant to happen but from what I see its not a big issue.

**Comment by HoverEpic** [comment]
This is the raknet server shutdown, I'll see if we can stop it properly later.

**Comment by DefinitlyEvil** [comment]
we are violent! >:D just shutdown with force! 
xD

**Comment by HoverEpic** [comment]
I've tried to work on this, but unsuccessfully, so let's do nothing.

**Comment by DefinitlyEvil** [comment]
not a big deal, just ignore those errors lol :P
