### ISSUE TITLE
Head item bug? 

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#185]
```
java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.dragonet.proxy.data.nbt.stream.NBTInputStream.readByte(NBTInputStream.java:65)
        at org.dragonet.proxy.data.nbt.tag.Tag.readNamedTag(Tag.java:85)
        at org.dragonet.proxy.data.nbt.tag.CompoundTag.load(CompoundTag.java:36)
        at org.dragonet.proxy.data.nbt.tag.ListTag.load(ListTag.java:50)
        at org.dragonet.proxy.data.nbt.tag.Tag.readNamedTag(Tag.java:94)
        at org.dragonet.proxy.data.nbt.tag.CompoundTag.load(CompoundTag.java:36)
        at org.dragonet.proxy.data.nbt.tag.Tag.readNamedTag(Tag.java:94)
        at org.dragonet.proxy.data.nbt.NBTIO.read(NBTIO.java:44)
        at org.dragonet.proxy.data.nbt.NBTIO.read(NBTIO.java:39)
        at org.dragonet.proxy.data.nbt.NBTIO.read(NBTIO.java:57)
        at org.dragonet.proxy.utilities.BinaryStream.getSlot(BinaryStream.java:309)
        at org.dragonet.proxy.protocol.packets.MobEquipmentPacket.decodePayload(MobEquipmentPacket.java:35)
        at org.dragonet.proxy.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.proxy.protocol.Protocol.decodeSingle(Protocol.java:134)
        at org.dragonet.proxy.protocol.Protocol.decode(Protocol.java:110)
        at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by HoverEpic** [comment]
how to reproduce?

**Comment by DefinitlyEvil** [comment]
join `play.mcpz.net` i think
