### ISSUE TITLE
various errors about the new update

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#186]
```
java.lang.NullPointerException
        at org.dragonet.proxy.network.translator.pc.PCSetTitlePacketTranslator.translate(PCSetTitlePacketTranslator.java:24)
        at org.dragonet.proxy.network.translator.pc.PCSetTitlePacketTranslator.translate(PCSetTitlePacketTranslator.java:9)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:148)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:335)
        at java.lang.Thread.run(Thread.java:745)
java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.dragonet.proxy.data.nbt.stream.NBTInputStream.readByte(NBTInputStream.java:65)
        at org.dragonet.proxy.data.nbt.tag.Tag.readNamedTag(Tag.java:85)
        at org.dragonet.proxy.data.nbt.tag.CompoundTag.load(CompoundTag.java:36)
        at org.dragonet.proxy.data.nbt.tag.ListTag.load(ListTag.java:50)
        at org.dragonet.proxy.data.nbt.tag.Tag.readNamedTag(Tag.java:94)
        at org.dragonet.proxy.data.nbt.tag.CompoundTag.load(CompoundTag.java:36)
        at org.dragonet.proxy.data.nbt.tag.Tag.readNamedTag(Tag.java:94)
        at org.dragonet.proxy.data.nbt.NBTIO.read(NBTIO.java:44)
        at org.dragonet.proxy.data.nbt.NBTIO.read(NBTIO.java:39)
        at org.dragonet.proxy.data.nbt.NBTIO.read(NBTIO.java:57)
        at org.dragonet.proxy.utilities.BinaryStream.getSlot(BinaryStream.java:309)
        at org.dragonet.proxy.protocol.packets.MobEquipmentPacket.decodePayload(MobEquipmentPacket.java:35)
        at org.dragonet.proxy.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.proxy.protocol.Protocol.decodeSingle(Protocol.java:134)
        at org.dragonet.proxy.protocol.Protocol.decode(Protocol.java:110)
        at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.ArrayIndexOutOfBoundsException: 833
        at org.dragonet.proxy.utilities.BinaryStream.getByte(BinaryStream.java:196)
        at org.dragonet.proxy.utilities.VarInt.read(VarInt.java:186)
        at org.dragonet.proxy.utilities.VarInt.readUnsignedVarInt(VarInt.java:75)
        at org.dragonet.proxy.utilities.BinaryStream.getUnsignedVarInt(BinaryStream.java:379)
        at org.dragonet.proxy.utilities.BinaryStream.getByteArray(BinaryStream.java:361)
        at org.dragonet.proxy.utilities.BinaryStream.getString(BinaryStream.java:370)
        at org.dragonet.proxy.utilities.BinaryStream.getSlot(BinaryStream.java:319)
        at org.dragonet.proxy.protocol.packets.MobEquipmentPacket.decodePayload(MobEquipmentPacket.java:35)
        at org.dragonet.proxy.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.proxy.protocol.Protocol.decodeSingle(Protocol.java:134)
        at org.dragonet.proxy.protocol.Protocol.decode(Protocol.java:110)
        at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
        at org.dragonet.proxy.network.translator.EntityMetaTranslator.translateToPE(EntityMetaTranslator.java:262)
        at org.dragonet.proxy.network.translator.pc.PCSpawnMobPacketTranslator.translate(PCSpawnMobPacketTranslator.java:41)
        at org.dragonet.proxy.network.translator.pc.PCSpawnMobPacketTranslator.translate(PCSpawnMobPacketTranslator.java:24)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:148)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:335)
        at java.lang.Thread.run(Thread.java:745)
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
        at org.dragonet.proxy.network.translator.EntityMetaTranslator.translateToPE(EntityMetaTranslator.java:262)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:43)
        at org.dragonet.proxy.network.translator.pc.PCEntityMetadataPacketTranslator.translate(PCEntityMetadataPacketTranslator.java:30)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:148)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:335)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by HoverEpic** [comment]
It's ok.
