### ISSUE TITLE
decode fail?

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#187]
```
java -jar dragonproxy-0.3.4.1.jar
>[11:17:21] [INFO] Saving console output enabled
[11:17:21] [WARNING] This is a development build. It may contain bugs. Do not us                                                                                                                                                             e on production.

[11:17:21] [INFO] Starting up DragonProxy, version: 0.3.4.1 (65a347a) ...
[11:17:21] [INFO] Supported version of Minecraft PC/Mac: 1.12.2
[11:17:21] [INFO] Supported version of Minecraft: Pocket/Windows 10 Edition: v1.                                                                                                                                                             2.7
[11:17:21] [INFO] Creating thread pool(Size:16)...
[11:17:21] [INFO] Binding on 0.0.0.0:19132 ...
[11:17:21] [INFO] The proxy has started!
[11:17:21] [DEBUG] PING /xx.xx.x.xxx:xxxxx
[11:17:21] [DEBUG] CLIENT CONNECT
Jan 03, 2018 11:17:32 AM com.fasterxml.jackson.databind.ext.Java7Support <clinit                                                                                                                                                             >
WARNUNG: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 s                                                                                                                                                             upport added
The LoginPacket has been successfully verified for integrity
[11:17:21] [DEBUG] CLIENT PROTOCOL = 160
[11:17:21] [INFO] Player MCPEExpert[/] connected!
[11:17:21] [DEBUG] Login online mode, sending placeholder datas
[11:17:21] [INFO] Player MCPEExpert[/] logged in via Minecraft                                                                                                                                                              account.
[11:17:21] [INFO] Bridge established for player MCPEExpert[/]!
java.lang.NullPointerException
        at org.dragonet.proxy.network.translator.pc.PCSetTitlePacketTranslator.t                                                                                                                                                             ranslate(PCSetTitlePacketTranslator.java:24)
        at org.dragonet.proxy.network.translator.pc.PCSetTitlePacketTranslator.t                                                                                                                                                             ranslate(PCSetTitlePacketTranslator.java:9)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(Pac                                                                                                                                                             ketTranslatorRegister.java:148)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDow                                                                                                                                                             nstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.cal                                                                                                                                                             l(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.j                                                                                                                                                             ava:142)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:                                                                                                                                                             335)
        at java.lang.Thread.run(Thread.java:748)
[11:17:21] [DEBUG] Spawning MCPEExpert in world -1 at -2.432695550941156/68.7200                                                                                                                                                             0001102685/0.10500919770301043
java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.dragonet.proxy.data.nbt.stream.NBTInputStream.readByte(NBTInputSt                                                                                                                                                             ream.java:65)
        at org.dragonet.proxy.data.nbt.tag.Tag.readNamedTag(Tag.java:85)
        at org.dragonet.proxy.data.nbt.tag.CompoundTag.load(CompoundTag.java:36)
        at org.dragonet.proxy.data.nbt.tag.ListTag.load(ListTag.java:50)
        at org.dragonet.proxy.data.nbt.tag.Tag.readNamedTag(Tag.java:94)
        at org.dragonet.proxy.data.nbt.tag.CompoundTag.load(CompoundTag.java:36)
        at org.dragonet.proxy.data.nbt.tag.Tag.readNamedTag(Tag.java:94)
        at org.dragonet.proxy.data.nbt.NBTIO.read(NBTIO.java:44)
        at org.dragonet.proxy.data.nbt.NBTIO.read(NBTIO.java:39)
        at org.dragonet.proxy.data.nbt.NBTIO.read(NBTIO.java:57)
        at org.dragonet.proxy.utilities.BinaryStream.getSlot(BinaryStream.java:3                                                                                                                                                             09)
        at org.dragonet.proxy.protocol.packets.MobEquipmentPacket.decodePayload(                                                                                                                                                             MobEquipmentPacket.java:35)
        at org.dragonet.proxy.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.proxy.protocol.Protocol.decodeSingle(Protocol.java:134)
        at org.dragonet.proxy.protocol.Protocol.decode(Protocol.java:110)
        at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.ja                                                                                                                                                             va:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51                                                                                                                                                             1)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                                                                                             access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                                                                                             run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                                                             java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                                                             .java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 833
        at org.dragonet.proxy.utilities.BinaryStream.getByte(BinaryStream.java:1                                                                                                                                                             96)
        at org.dragonet.proxy.utilities.VarInt.read(VarInt.java:186)
        at org.dragonet.proxy.utilities.VarInt.readUnsignedVarInt(VarInt.java:75                                                                                                                                                             )
        at org.dragonet.proxy.utilities.BinaryStream.getUnsignedVarInt(BinaryStr                                                                                                                                                             eam.java:379)
        at org.dragonet.proxy.utilities.BinaryStream.getByteArray(BinaryStream.j                                                                                                                                                             ava:361)
        at org.dragonet.proxy.utilities.BinaryStream.getString(BinaryStream.java                                                                                                                                                             :370)
        at org.dragonet.proxy.utilities.BinaryStream.getSlot(BinaryStream.java:3                                                                                                                                                             19)
        at org.dragonet.proxy.protocol.packets.MobEquipmentPacket.decodePayload(                                                                                                                                                             MobEquipmentPacket.java:35)
        at org.dragonet.proxy.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.proxy.protocol.Protocol.decodeSingle(Protocol.java:134)
        at org.dragonet.proxy.protocol.Protocol.decode(Protocol.java:110)
        at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.ja                                                                                                                                                             va:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51                                                                                                                                                             1)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                                                                                             access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                                                                                             run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                                                             java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                                                             .java:624)
        at java.lang.Thread.run(Thread.java:748)
can not decode for pid 0x25
decode fail
```

**Comment by DefinitlyEvil** [comment]
decode fail is normal and errors are not the same thing, duplicated issue.
