### ISSUE TITLE
Held skull item on playinfinity.de

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#198]
```
java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.dragonet.common.mcbedrock.data.nbt.stream.NBTInputStream.readByte                                                                                                                                                             (NBTInputStream.java:65)
        at org.dragonet.common.mcbedrock.data.nbt.tag.Tag.readNamedTag(Tag.java:                                                                                                                                                             85)
        at org.dragonet.common.mcbedrock.data.nbt.tag.CompoundTag.load(CompoundT                                                                                                                                                             ag.java:36)
        at org.dragonet.common.mcbedrock.data.nbt.tag.ListTag.load(ListTag.java:                                                                                                                                                             50)
        at org.dragonet.common.mcbedrock.data.nbt.tag.Tag.readNamedTag(Tag.java:                                                                                                                                                             94)
        at org.dragonet.common.mcbedrock.data.nbt.tag.CompoundTag.load(CompoundT                                                                                                                                                             ag.java:36)
        at org.dragonet.common.mcbedrock.data.nbt.tag.Tag.readNamedTag(Tag.java:                                                                                                                                                             94)
        at org.dragonet.common.mcbedrock.data.nbt.NBTIO.read(NBTIO.java:44)
        at org.dragonet.common.mcbedrock.data.nbt.NBTIO.read(NBTIO.java:61)
        at org.dragonet.common.mcbedrock.utilities.BinaryStream.getSlot(BinarySt                                                                                                                                                             ream.java:308)
        at org.dragonet.common.mcbedrock.protocol.packets.MobEquipmentPacket.dec                                                                                                                                                             odePayload(MobEquipmentPacket.java:35)
        at org.dragonet.common.mcbedrock.protocol.PEPacket.decode(PEPacket.java:                                                                                                                                                             34)
        at org.dragonet.common.mcbedrock.protocol.Protocol.decodeSingle(Protocol                                                                                                                                                             .java:136)
        at org.dragonet.common.mcbedrock.protocol.Protocol.decode(Protocol.java:                                                                                                                                                             112)
        at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.ja                                                                                                                                                             va:72)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51                                                                                                                                                             1)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                                                                                             access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                                                                                             run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                                                             java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                                                             .java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 1147
        at org.dragonet.common.mcbedrock.utilities.BinaryStream.getByte(BinarySt                                                                                                                                                             ream.java:195)
        at org.dragonet.common.mcbedrock.utilities.VarInt.read(VarInt.java:186)
        at org.dragonet.common.mcbedrock.utilities.VarInt.readUnsignedVarInt(Var                                                                                                                                                             Int.java:75)
        at org.dragonet.common.mcbedrock.utilities.BinaryStream.getUnsignedVarIn                                                                                                                                                             t(BinaryStream.java:378)
        at org.dragonet.common.mcbedrock.utilities.BinaryStream.getByteArray(Bin                                                                                                                                                             aryStream.java:360)
        at org.dragonet.common.mcbedrock.utilities.BinaryStream.getString(Binary                                                                                                                                                             Stream.java:369)
        at org.dragonet.common.mcbedrock.utilities.BinaryStream.getSlot(BinarySt                                                                                                                                                             ream.java:318)
        at org.dragonet.common.mcbedrock.protocol.packets.MobEquipmentPacket.dec                                                                                                                                                             odePayload(MobEquipmentPacket.java:35)
        at org.dragonet.common.mcbedrock.protocol.PEPacket.decode(PEPacket.java:                                                                                                                                                             34)
        at org.dragonet.common.mcbedrock.protocol.Protocol.decodeSingle(Protocol                                                                                                                                                             .java:136)
        at org.dragonet.common.mcbedrock.protocol.Protocol.decode(Protocol.java:                                                                                                                                                             112)
        at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.ja                                                                                                                                                             va:72)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51                                                                                                                                                             1)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                                                                                             access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                                                                                             run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                                                             java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                                                             .java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by DefinitlyEvil** [comment]
I think it has something to do with #185

**Comment by ErkamKahriman** [comment]
It can be

**Comment by HoverEpic** [comment]
Closing dupplicated, tanks for report.
