### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by Encritary** [DragonetMC/DragonProxy#214]
```
Jan 11, 2018 7:03:34 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
Failed to verify the integrity of the LoginPacket
java.lang.NullPointerException: No trusted public key found in chain
	at org.dragonet.common.mcbedrock.utilities.LoginChainDecoder.decode(LoginChainDecoder.java:99)
	at org.dragonet.common.mcbedrock.protocol.packets.LoginPacket.decodePayload(LoginPacket.java:42)
	at org.dragonet.common.mcbedrock.protocol.PEPacket.decode(PEPacket.java:34)
	at org.dragonet.common.mcbedrock.protocol.Protocol.decodeSingle(Protocol.java:136)
	at org.dragonet.common.mcbedrock.protocol.Protocol.decode(Protocol.java:112)
	at org.dragonet.proxy.network.PEPacketProcessor.run(PEPacketProcessor.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ApocalypsjeNL** [comment]
Which Java version are you using?, and are you using an xbox live connected account?

**Comment by Encritary** [comment]
@ApocalypsjeNL latest Java 8. Logged in

**Comment by HoverEpic** [comment]
Is your client connected to XBoxLive? if not, turn off xbox live auth in the config file.

**Comment by DefinitlyEvil** [comment]
disable xbox verification in `config.yml` or login as you should!

**Comment by HoverEpic** [comment]
Is it ok?

**Comment by HoverEpic** [comment]
`Failed to verify the integrity of the LoginPacket`
means the login packet does not contain auth chain, so your PE client is not logged in.
To remove this error, do what @DefinitlyEvil said.
