### ISSUE TITLE
Offline Xbox account bug

### ISSUE THREAD

**Issue by Hagb** [DragonetMC/DragonProxy#231]
I compiled the lastest DragonProxy and had a try. But when Minecraft PE tried to connected  to DragonProxy, it failed and proxy told me :
```
[16:07:02] [DEBUG] CLIENT CONNECT
30, 2018 4:07:07 org.dragonet.common.utilities.LoginChainDecoder decode  
INFO: The LoginPacket has been successfully verified for integrity  
Exception in thread "Thread-0" java.lang.ExceptionInInitializerError  
	at org.dragonet.common.utilities.LoginChainDecoder.decode(LoginChainDecoder.java:149)  
	at org.dragonet.protocol.packets.LoginPacket.decodePayload(LoginPacket.java:42)  
	at org.dragonet.protocol.PEPacket.decode(PEPacket.java:34)  
	at org.dragonet.protocol.Protocol.decodeSingle(Protocol.java:138)  
	at org.dragonet.protocol.Protocol.decode(Protocol.java:114)  
	at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor.java:78)  
	at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.java:506)  
	at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.java:38)  
	at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:236)  
	at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)  
Caused by: java.lang.IllegalArgumentException: VarLong too big  
	at org.dragonet.common.utilities.VarInt.read(VarInt.java:189)  
	at org.dragonet.common.utilities.VarInt.readUnsignedVarInt(VarInt.java:75)  
	at org.dragonet.common.utilities.BinaryStream.getUnsignedVarInt(BinaryStream.java:380)  
	at org.dragonet.common.utilities.BinaryStream.getByteArray(BinaryStream.java:362)  
	at org.dragonet.common.data.entity.Skin.read(Skin.java:56)  
	at org.dragonet.common.data.entity.Skin.<clinit>(Skin.java:34)  
	... 10 more 
```

Below is a part of my config.yml :  
```
udp_bind_ip: '0.0.0.0'  
udp_bind_port: 19132  
default_server: 'my_pc_server'  
  remote_servers:  
    !!org.dragonet.proxy.DesktopServer
    remote_addr: '127.0.0.1'
    remote_port: 25565
mode: offline  
authenticate_players: false  
command_prefix: '/'  
max_players: 10  
log_console: true  
log_debug: true  
thread_pool_size: 12  
```
Sorry for my bad English ^_^

**Comment by DefinitlyEvil** [comment]
which version of MCPE and DragonProxy?

**Comment by Hagb** [comment]
@DefinitlyEvil 
I had tried MCPE 1.2.9 and 1.2.8. and both of them caused the same thing. DragonProxy compiled by me was from the lastest source code in https://github.com/DragonetMC/DragonProxy.
Thank you! And sorry for my bad English again.

**Comment by HoverEpic** [comment]
You have to disable pe account validation in DragonProxy.

**Comment by Hagb** [comment]
@HoverEpic I had set authenticate_players: false .

**Comment by HoverEpic** [comment]
My lastest deleted message:
> You have to disable pe account validation in DragonProxy.

There is probably a problem with the skin system in offline mode.

**Comment by Hagb** [comment]
@HoverEpic  I change "mode: offline" into "mode: online" but this problem still happen. By the way, DragonProxy 0.3.4.2 don't have this problem.

**Comment by HoverEpic** [comment]
Seems `authenticate_players: false` in config is not working. Thanks for reporting.

**Comment by HoverEpic** [comment]
Continue talking about this problem on #238
