### ISSUE TITLE
Error on login, skin crashing

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#238]
mode: online + authenticate_players: true

```févr. 08, 2018 2:19:40 PM org.dragonet.common.utilities.LoginChainDecoder decode
INFOS: The LoginPacket has been successfully verified for integrity
Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
	at org.dragonet.common.utilities.LoginChainDecoder.decode(LoginChainDecoder.java:149)
	at org.dragonet.protocol.packets.LoginPacket.decodePayload(LoginPacket.java:42)
	at org.dragonet.protocol.PEPacket.decode(PEPacket.java:34)
	at org.dragonet.protocol.Protocol.decodeSingle(Protocol.java:138)
	at org.dragonet.protocol.Protocol.decode(Protocol.java:114)
	at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor.java:78)
	at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.java:506)
	at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.java:38)
	at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:236)
	at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)
Caused by: java.lang.IllegalArgumentException: VarLong too big
	at org.dragonet.common.utilities.VarInt.read(VarInt.java:189)
	at org.dragonet.common.utilities.VarInt.readUnsignedVarInt(VarInt.java:75)
	at org.dragonet.common.utilities.BinaryStream.getUnsignedVarInt(BinaryStream.java:380)
	at org.dragonet.common.utilities.BinaryStream.getByteArray(BinaryStream.java:362)
	at org.dragonet.common.data.entity.Skin.read(Skin.java:58)
	at org.dragonet.common.data.entity.Skin.<clinit>(Skin.java:36)
	... 10 more```

**Comment by HoverEpic** [comment]
Seems profile decoding is not ok, i'm trying to fix the problem.

**Comment by sgdc3** [comment]
Happens also with mode: offline and authenticate: false

**Comment by HoverEpic** [comment]
oh ok, with release or latest (or both)?
I'm trying to resolve this since 5 hours, if someone have a hint (or better, a fix =P).

**Comment by sgdc3** [comment]
only latest

**Comment by HoverEpic** [comment]
I think we need to fix 1.2.10 login (#237) first, then search for this.

**Comment by HoverEpic** [comment]
Now, we can take a look at this, it's about Skin.

**Comment by HoverEpic** [comment]
Come from org.dragonet.common.data.entity.Skin.<clinit>(Skin.java:36), seems the skin stsem is buggy.

**Comment by sgdc3** [comment]
can we disable it in the meantime?

**Comment by HoverEpic** [comment]
I don't know, i have not time actualy to try, maybe next week...

**Comment by HoverEpic** [comment]
Error is fixed, players can login, but every other players have black skin, i'm opening a new issue for that.
