### ISSUE TITLE
no players

### ISSUE THREAD

**Issue by thelex0** [DragonetMC/DragonProxy#241]
players are not displayed
DragonProxy: latest, BungeeCord: latest, spigot 1.8.8 + ViaVersion

**Comment by Ajaxan** [comment]
Having the same issue. Players are not displayed.

**Comment by HoverEpic** [comment]
Is it only on a ViaVersion server or it appeared also with a 1.12.2 server? (hypixel's working on yesterday test)

**Comment by Crypt97** [comment]
I do not see them and I used 1.12.2!

**Comment by Ajaxan** [comment]
I encountered this error while running a PaperSpigot server through a bungeecoord proxy on version 1.12.2

**Comment by michaeljfarr** [comment]
It looks like an issue in AddPlayerPacket where thirdpartyName is null is causing a bunch of these issues. Here is the stack trace I see (on a 1.12.2 server).

java.lang.NullPointerException
        at org.dragonet.proxy.utilities.BinaryStream.putString(BinaryStream.java:374)
        at org.dragonet.proxy.protocol.packets.AddPlayerPacket.encodePayload(AddPlayerPacket.java:46)
        at org.dragonet.proxy.protocol.PEPacket.encode(PEPacket.java:28)
        at org.dragonet.proxy.network.UpstreamSession.sendPacket(UpstreamSession.java:177)
        at org.dragonet.proxy.network.UpstreamSession.sendPacket(UpstreamSession.java:170)
        at org.dragonet.proxy.network.cache.CachedEntity.spawn(CachedEntity.java:150)
        at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:12)
        at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:8)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:149)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by HoverEpic** [comment]
Looks like this break on last update, can you give me the dragonproxy version showed in the beginning of the log?

**Comment by michaeljfarr** [comment]
This is what I had:
java -jar dragonproxy-0.3.4.3.jar --debug
[21:36:25] [INFO] Saving console output enabled
[21:36:25] [WARNING] This is a development build. It may contain bugs. Do not use on production.

[21:36:25] [INFO] Proxy is running in debug mode.
[21:36:25] [INFO] Starting up DragonProxy, version: 0.3.4.3 (dacc2da) ...

**Comment by HoverEpic** [comment]
Fixed on master branch, try with https://ci.codemc.org/view/DragonetMC/job/DragonProxy/lastSuccessfulBuild/artifact/proxy/target/dragonproxy-0.3.4.3-SNAPSHOT.jar
