### ISSUE TITLE
Idk what this is 

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#251]
```
java.lang.IndexOutOfBoundsException
        at com.github.steveice10.mc.protocol.data.game.chunk.FlexibleStorage.set(FlexibleStorage.java:75)
        at com.github.steveice10.mc.protocol.data.game.chunk.BlockStorage.set(BlockStorage.java:110)
        at org.dragonet.proxy.network.cache.ChunkCache.update(ChunkCache.java:117)
        at org.dragonet.proxy.network.translator.pc.PCMultiBlockChangePacketTranslator.translate(PCMultiBlockChangePacketTranslator.java:30)
        at org.dragonet.proxy.network.translator.pc.PCMultiBlockChangePacketTranslator.translate(PCMultiBlockChangePacketTranslator.java:23)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:160)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:87)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by HoverEpic** [comment]
I just see that error, i'm on it.

**Comment by HoverEpic** [comment]
fixed
