### ISSUE TITLE
If i hold a head in my hand ..

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#252]
```
java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.dragonet.common.data.nbt.stream.NBTInputStream.readByte(NBTInputStream.java:65)
        at org.dragonet.common.data.nbt.tag.Tag.readNamedTag(Tag.java:85)
        at org.dragonet.common.data.nbt.tag.CompoundTag.load(CompoundTag.java:36)
        at org.dragonet.common.data.nbt.tag.ListTag.load(ListTag.java:50)
        at org.dragonet.common.data.nbt.tag.Tag.readNamedTag(Tag.java:94)
        at org.dragonet.common.data.nbt.tag.CompoundTag.load(CompoundTag.java:36)
        at org.dragonet.common.data.nbt.tag.Tag.readNamedTag(Tag.java:94)
        at org.dragonet.common.data.nbt.NBTIO.read(NBTIO.java:44)
        at org.dragonet.common.data.nbt.NBTIO.read(NBTIO.java:61)
        at org.dragonet.common.utilities.BinaryStream.getSlot(BinaryStream.java:322)
        at org.dragonet.protocol.packets.MobEquipmentPacket.decodePayload(MobEquipmentPacket.java:35)
        at org.dragonet.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.protocol.Protocol.decodeSingle(Protocol.java:141)
        at org.dragonet.protocol.Protocol.decode(Protocol.java:117)
        at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor.java:95)
        at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.java:487)
        at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.java:38)
        at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:235)
        at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)
java.lang.ArrayIndexOutOfBoundsException
```

**Comment by HoverEpic** [comment]
Yes heads are not currently supported

**Comment by Erkam246** [comment]
ok

**Comment by HoverEpic** [comment]
dupplicated #185
