### ISSUE TITLE
Plugin: Error on join chunks doesnt load

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#253]
```
[DragonProxy-ServerAddon] Plugin DragonProxy-ServerAddon v0.1 generated an exception whilst handling plugin message
java.lang.NoClassDefFoundError: org/dragonet/common/utilities/BinaryStream
        at org.dragonet.plugin.bukkit.DPPluginMessageListener.onPluginMessageReceived(DPPluginMessageListener.java:21) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2576) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: org.dragonet.common.utilities.BinaryStream
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
        ... 14 more
```

**Comment by HoverEpic** [comment]
The plugin is broken too, disable it for now.
