### ISSUE TITLE
Decode fails...

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#272]
## I think this will be given as error if i place blocks...
```
java.lang.IllegalArgumentException: VarLong too big
        at org.dragonet.common.utilities.VarInt.read(VarInt.java:189)
        at org.dragonet.common.utilities.VarInt.readUnsignedVarInt(VarInt.java:7                                                                                                                                                             5)
        at org.dragonet.common.utilities.VarInt.readVarInt(VarInt.java:59)
        at org.dragonet.common.utilities.BinaryStream.getVarInt(BinaryStream.jav                                                                                                                                                             a:404)
        at org.dragonet.common.utilities.BinaryStream.getBlockPosition(BinaryStr                                                                                                                                                             eam.java:428)
        at org.dragonet.protocol.packets.InventoryTransactionPacket.decodePayloa                                                                                                                                                             d(InventoryTransactionPacket.java:130)
        at org.dragonet.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.protocol.Protocol.decodeSingle(Protocol.java:141)
        at org.dragonet.protocol.Protocol.decode(Protocol.java:117)
        at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor                                                                                                                                                             .java:96)
        at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.jav                                                                                                                                                             a:479)
        at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.jav                                                                                                                                                             a:38)
        at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:257)
        at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)
[20:03:47][INFORMATION] decode fail
pl
[20:04:20][INFORMATION] [Console] Executing command: pl
[20:04:20][WARNUNG] §cCommand not found!
java.lang.IllegalArgumentException: VarLong too big
        at org.dragonet.common.utilities.VarInt.read(VarInt.java:189)
        at org.dragonet.common.utilities.VarInt.readUnsignedVarInt(VarInt.java:75)
        at org.dragonet.common.utilities.BinaryStream.getUnsignedVarInt(BinaryStream.java:396)
        at org.dragonet.common.utilities.BinaryStream.getBlockPosition(BinaryStream.java:428)
        at org.dragonet.protocol.packets.InventoryTransactionPacket.decodePayload(InventoryTransactionPacket.java:129)
        at org.dragonet.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.protocol.Protocol.decodeSingle(Protocol.java:141)
        at org.dragonet.protocol.Protocol.decode(Protocol.java:117)
        at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor.java:96)
        at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.java:479)
        at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.java:38)
        at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:257)
        at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)
[20:04:53][INFORMATION] decode fail
```

**Comment by HoverEpic** [comment]
Do you remember what type of item was it? and the location in the world? i want to reproduce.

**Comment by HoverEpic** [comment]
dupplicated #261, closing the other
