### ISSUE TITLE
2x1 water bug

### ISSUE THREAD

**Issue by ZachPro** [DragonetMC/DragonProxy#277]
When you travel up water, within a 2x1 location, you are stuck in a glitch.

`java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source)
        at java.util.HashMap$KeyIterator.next(Unknown Source)
        at java.util.AbstractCollection.addAll(Unknown Source)
        at java.util.HashSet.<init>(Unknown Source)
        at org.dragonet.proxy.network.cache.ChunkCache.sendOrderedChunks(ChunkCache.java:196)
        at org.dragonet.proxy.network.translator.pe.PEMovePlayerPacketTranslator.translate(PEMovePlayerPacketTranslator.java:73)
        at org.dragonet.proxy.network.translator.pe.PEMovePlayerPacketTranslator.translate(PEMovePlayerPacketTranslator.java:30)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPC(PacketTranslatorRegister.java:178)
        at org.dragonet.proxy.network.PEPacketProcessor.handlePacket(PEPacketProcessor.java:191)
        at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor.java:107)
        at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.java:496)
        at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.java:38)
        at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:280)
        at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)`

![image](https://user-images.githubusercontent.com/1770701/36994382-eee5d3ba-207e-11e8-9da0-e4f5b1b326b1.png)

**Comment by HoverEpic** [comment]
I need to work again on chunk engine.
