### ISSUE TITLE
Inventory transaction stacktrace

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#283]
`java.lang.IllegalArgumentException: VarLong too big
        at org.dragonet.common.utilities.VarInt.read(VarInt.java:189)
        at org.dragonet.common.utilities.VarInt.readUnsignedVarInt(VarInt.java:75)
        at org.dragonet.common.utilities.VarInt.readVarInt(VarInt.java:59)
        at org.dragonet.common.utilities.BinaryStream.getVarInt(BinaryStream.java:404)
        at org.dragonet.common.utilities.BinaryStream.getBlockPosition(BinaryStream.java:428)
        at org.dragonet.protocol.packets.InventoryTransactionPacket.decodePayload(InventoryTransactionPacket.java:129)
        at org.dragonet.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.protocol.Protocol.decodeSingle(Protocol.java:141)
        at org.dragonet.protocol.Protocol.decode(Protocol.java:117)
        at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor.java:98)
        at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.java:496)
        at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.java:38)
        at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:280)
        at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)`

Protocol errors are breaking main ticker, errors should be handled a different way, and not break the upstream session.

**Comment by HoverEpic** [comment]
Chould be fixed
