### ISSUE TITLE
Can't join DragonProxy

### ISSUE THREAD

**Issue by ghost** [DragonetMC/DragonProxy#302]
![screenshot_2018-03-21-18-01-03](https://user-images.githubusercontent.com/17501381/37724832-ed6cb39a-2d31-11e8-8d43-677a1a71526f.png)

I get this when i try to join the DragonProxy(Never saw this error in my minecraft life) i use version 1.2.10(MCPE) i have no firewall and the java server i am trying to join is online any help is appreciated

**Comment by lukeeey** [comment]
We've seen this a lot lately and i forgot how to fix it, or even if you can. You can try changing both the proxy and server to offline mode for a temporary fix.

**Comment by ghost** [comment]
This is the error i get if you need:
```
com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
Mar 21, 2018 6:04:54 PM org.dragonet.common.utilities.LoginChainDecoder decode
INFO: Failed to verify the integrity of the LoginPacket
com.auth0.jwt.exceptions.SignatureVerificationException: The Token's Signature resulted invalid when verified using the Algorithm: SHA384withECDSA
	at com.auth0.jwt.algorithms.ECDSAAlgorithm.verify(ECDSAAlgorithm.java:50)
	at org.dragonet.common.utilities.LoginChainDecoder.decode(LoginChainDecoder.java:102)
	at org.dragonet.protocol.packets.LoginPacket.decodePayload(LoginPacket.java:42)
	at org.dragonet.protocol.PEPacket.decode(PEPacket.java:34)
	at org.dragonet.protocol.Protocol.decodeSingle(Protocol.java:141)
	at org.dragonet.protocol.Protocol.decode(Protocol.java:117)
	at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor.java:98)
	at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.java:496)
	at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.java:38)
	at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:280)
	at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)
```

**Comment by lukeeey** [comment]
Try changing `authenticate_players` to `false` in your config.yml

**Comment by HoverEpic** [comment]
Hey,  @am714 you are using cracked game?

**Comment by ghost** [comment]
No i bought the game and downloaded old apk from some website

**Comment by lukeeey** [comment]
i use cracked it makes no difference.

@am714 Did you try disabling authenticate_players?

**Comment by HoverEpic** [comment]
weird, last time someone have this problem, that was that.
are you logged in xbox live account?

**Comment by lukeeey** [comment]
@HoverEpic You have to be to play servers

**Comment by ghost** [comment]
yes now i think i will just play cracked mode servers:

```
com.github.steveice10.mc.auth.exception.request.ServiceUnavailableException: Could not make request to 'https://authserver.mojang.com/authenticate'.
	at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:64)
	at com.github.steveice10.mc.auth.service.AuthenticationService.loginWithPassword(AuthenticationService.java:302)
	at com.github.steveice10.mc.auth.service.AuthenticationService.login(AuthenticationService.java:218)
	at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:192)
	at org.dragonet.proxy.network.UpstreamSession.lambda$authenticate$0(UpstreamSession.java:285)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: java.lang.IllegalStateException
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.github.steveice10.mc.auth.util.HTTP.performPostRequest(HTTP.java:182)
	at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:61)
	... 11 more
Caused by: java.lang.IllegalStateException
	at sun.security.ec.ECDHKeyAgreement.deriveKey(Native Method)
	at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:130)
	at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:163)
	at javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:648)
	at sun.security.ssl.ECDHCrypt.getAgreedSecret(ECDHCrypt.java:101)
	at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1067)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	... 19 more
```

**Comment by HoverEpic** [comment]
Whaaaaat? that part is not supposed to break ><

**Comment by lukeeey** [comment]
It looks like an SSL error. Do you have any proxies such as Fiddler running? (i have no idea just guessing)

**Comment by lukeeey** [comment]
What did you even change to get that error?

**Comment by HoverEpic** [comment]
i think you have a java + dragonproxy issue.
DragonProxy use some high crypto functions, that seems not present on your system.
can you tell me what version you'r runing? (`java -version`)

**Comment by ghost** [comment]
i think it is something related on how the proxy connect to mojang servers and no i have no proxy running on DMZ i can connect fine using minechat and my laptop i changed authenticate_players to false and tried to login to my account

**Comment by lukeeey** [comment]
Did it not happen when authenticate_players was true? If so, try enabling it again.

**Comment by ghost** [comment]
with authenticate_players i get that school error

**Comment by lukeeey** [comment]
Well, fuck. Please show us the output of `java --version`

**Comment by ghost** [comment]
openjdk version "1.8.0_03-Ubuntu"
OpenJDK Runtime Environment (build 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03)
OpenJDK Zero VM (build 25.03-b03, interpreted mode)

it says jdk because i tried installing it after installing jre just to test if it was needed

**Comment by lukeeey** [comment]
Ah. You are using OpenJDK Zero. I'm not familiar with this, but it might not contain the crypto functions that we need.

Can you install normal JDK?

**Comment by ghost** [comment]
works now but you should fix the authenticate players anyway

**Comment by lukeeey** [comment]
@am714  How did you fix it?

**Comment by ghost** [comment]
i installed the jdk you said

**Comment by ghost** [comment]
most of the times i just do apt-get install default-jdk

**Comment by lukeeey** [comment]
Ah ok

**Comment by ghost** [comment]
![screenshot_2018-03-21-19-11-56](https://user-images.githubusercontent.com/17501381/37728923-db9836bc-2d3b-11e8-99be-6fccd1475f57.png)
not wanna annoy you but sometimes my gui disappear while playing

**Comment by lukeeey** [comment]
That must be a client bug.

**Comment by lukeeey** [comment]
Join demo.dragonet.org
