### ISSUE TITLE
Server List

### ISSUE THREAD

**Issue by UnexMC** [DragonetMC/DragonProxy#319]
**I want to show the server in a Server List. But it does not work, the showing as offline.**

**Idk, if this is the error?**
```
[08:29:17][INFO ] 08:29:17 [WARN ] com.whirvis.jraknet.server.RakNetServer -> Handled exception java.lang.IndexOutOfBoundsException caused by address /151.80.36.203:37581

java.lang.IndexOutOfBoundsException: readerIndex(24) + length(8) exceeds writerIndex(24): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 24, widx: 24, cap: 24)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403)
        at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:812)
        at com.whirvis.jraknet.Packet.readLong(Packet.java:296)
        at com.whirvis.jraknet.protocol.status.UnconnectedPing.decode(UnconnectedPing.java:70)                                  at com.whirvis.jraknet.server.RakNetServer.handleMessage(RakNetServer.java:569)
        at com.whirvis.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:142)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1412)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:943)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IndexOutOfBoundsException: readerIndex(24) + length(8) exceeds writerIndex(24): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 24, widx: 24, cap: 24)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403)
        at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:812)
        at com.whirvis.jraknet.Packet.readLong(Packet.java:296)
        at com.whirvis.jraknet.protocol.status.UnconnectedPing.decode(UnconnectedPing.java:70)
        at com.whirvis.jraknet.server.RakNetServer.handleMessage(RakNetServer.java:569)
        at com.whirvis.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:142)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1412)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:943)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by lukeeey** [comment]
@Whirvis Do you know the cause of this?

**Comment by whirvis** [comment]
It looks like a bad packet being sent from an outside source. Do you know what is pinging the server?

**Comment by whirvis** [comment]
Also this might not be a bug even, bad packets sent by outside sources can cause errors and if they do they are ignored and the sender gets disconnected. However, I need to the see the UnconnectedPing packet to confirm that it is an error from the external source and not just JRakNet
