### ISSUE TITLE
Chunk errors

### ISSUE THREAD

**Issue by timriker** [DragonetMC/DragonProxy#331]
Not sure what is causing this. I entered my spigot 1.12.2 server in the grief world (multiverse) at about 1800, -1600 and saw these errors. On warping (Essentials) to the entry survival world I was kicked. I reconnected, and I was where I warped to.

Are the getBlock OutOfBounds errors and issue or not?

```
[07:05:42][INFO ] getBlock(Position(x=176, y=-39, z=243))) fail to get chunk 11/-3/15
java.lang.ArrayIndexOutOfBoundsException: -3
        at org.dragonet.proxy.network.cache.ChunkCache.translateBlock(ChunkCache.java:158)
        at org.dragonet.proxy.network.translator.pe.PEMovePlayerPacketTranslator.translate(PEMovePlayerPacketTranslator.java:58)
        at org.dragonet.proxy.network.translator.pe.PEMovePlayerPacketTranslator.translate(PEMovePlayerPacketTranslator.java:30)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPC(PacketTranslatorRegister.java:182)
        at org.dragonet.proxy.network.PEPacketProcessor.handlePacket(PEPacketProcessor.java:191)
        at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor.java:107)
        at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.java:534)
        at org.dragonet.proxy.network.SessionRegister.lambda$onTick$0(SessionRegister.java:35)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.java:35)
        at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:309)
        at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)
[07:05:55][INFO ] Client TimRiker[/67.182.209.43:32947] disconnected! Reason: Client disconnect

```

I can send you the server address and grant to tp rights if you like.

Cool project!

**Comment by HoverEpic** [comment]
My fault ! "y" position should never be negative in Bedrock edition, and i haven't implemented a limiter.
The real question, is why the chunk engine trigger on a "y" negative block? There is nothing before 0 ><.
It's a known issue, and patching this is easy (just limit "y" 0 to 255 and ignore other values). Thanks for the reminder.

**Comment by HoverEpic** [comment]
Should be fixed in https://github.com/DragonetMC/DragonProxy/commit/06c6100ade6e3439b6d05a59d92fcd2865d0899d
