### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#334]
```
java.lang.NullPointerException
        at org.dragonet.proxy.network.translator.pc.PCSpawnParticlePacketTranslator.translate(PCSpawnParticlePacketTranslator.java:30)
        at org.dragonet.proxy.network.translator.pc.PCSpawnParticlePacketTranslator.translate(PCSpawnParticlePacketTranslator.java:20)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:163)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:94)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
        at java.lang.Thread.run(Thread.java:748)
com.whirvis.jraknet.session.TimeoutException: Session timeout
        at com.whirvis.jraknet.session.RakNetSession.update(RakNetSession.java:869)
        at com.whirvis.jraknet.server.RakNetServer.start(RakNetServer.java:822)
        at com.whirvis.jraknet.server.RakNetServer$1.run(RakNetServer.java:856)
```

**Comment by The-Drobe** [comment]
I have the same problem have you found a way around it yet?
