### ISSUE TITLE
DP spamming netty errors

### ISSUE THREAD

**Issue by k-jiang** [DragonetMC/DragonProxy#339]
DragonProxy spams a lot of repeating (every 5-20 seconds) exceptions like this:
```
[2018-07-07 14:20:19][INFO ] 14:20:19 [WARN ] io.netty.channel.AbstractChannel -> Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x15e8abd1]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:844)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:769)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:479)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
	at com.github.steveice10.packetlib.tcp.TcpClientSession$2.run(TcpClientSession.java:91)
	at com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:107)
	at com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:62)
	at org.dragonet.proxy.utilities.pingpassthrough.PingThread.run(PingThread.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 
[2018-07-07 14:20:19][INFO ] 14:20:19 [ERROR] io.netty.util.concurrent.DefaultPromise.rejectedExecution -> Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:844)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:769)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1148)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:490)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
	at com.github.steveice10.packetlib.tcp.TcpClientSession$2.run(TcpClientSession.java:91)
	at com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:107)
	at com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:62)
	at org.dragonet.proxy.utilities.pingpassthrough.PingThread.run(PingThread.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 
[2018-07-07 14:20:19][INFO ] 14:20:19 [ERROR] io.netty.util.concurrent.DefaultPromise.rejectedExecution -> Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:844)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:769)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:491)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
	at com.github.steveice10.packetlib.tcp.TcpClientSession$2.run(TcpClientSession.java:91)
	at com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:107)
	at com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:62)
	at org.dragonet.proxy.utilities.pingpassthrough.PingThread.run(PingThread.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Client version is probably Bedrock 1.4.1 according to [wiki](https://minecraft.gamepedia.com/Bedrock_Edition). The player seems playing a Nintendo Switch. However, the same issue occurs with other client as well (Andorid Minecraft 1.4.3 etc)
Backend: [Waterfall](https://github.com/WaterfallMC/Waterfall/) (a fork of BungeeCord).
Server version: PaperSpigot 1.12.2
Both `dragonproxy-plugin` and `dragonproxy-plugin-bungee` are installed.
Tested with [build 136](https://ci.codemc.org/job/DragonetMC/job/DragonProxy/146/).

I have asked my players for version confirmation. Also if you need more info or help for debugging please let me know.

**Comment by lukeeey** [comment]
You do realise it tells you the client version litterally on the play screen?

**Comment by lukeeey** [comment]
`dragonproxy-plugin` isnt a plugin. `dragonproxy-plugin-bungee`, `dragonproxy-plugin-bukkit` and `dragonproxy-plugin-universal` are, however.

**Comment by k-jiang** [comment]
Sorry that's a typo, for `dragonproxy-plugin` I means 'dragonproxy-plugin-spigot-0.3.4.5-SNAPSHOT.jar'

As for the client version, it is IOS Bedrock 1.4.3. The player complains that he can not teleport, open chests, or even move in game, only chat is available.

**Comment by k-jiang** [comment]
DP spams too many exceptions that it eventually out of memory:
```
[2018-07-07 20:24:16][INFO ] 20:24:16 [ERROR] io.netty.util.concurrent.DefaultPromise.rejectedExecution -> Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:844)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:769)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:491)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
	at com.github.steveice10.packetlib.tcp.TcpClientSession$2.run(TcpClientSession.java:91)
	at com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:107)
	at com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:62)
	at org.dragonet.proxy.utilities.pingpassthrough.PingThread.run(PingThread.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 
[2018-07-07 20:41:36][INFO ] 20:41:36 [WARN ] io.netty.channel.nio.NioEventLoop -> Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.iterator(ArrayList.java:840)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:692)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:472)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
 
[2018-07-07 20:42:13][INFO ] 20:42:13 [WARN ] io.netty.channel.nio.NioEventLoop -> Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
 
[2018-07-07 20:42:13][INFO ] 20:42:13 [WARN ] io.netty.channel.nio.NioEventLoop -> Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
 
[2018-07-07 20:42:13][INFO ] 20:42:13 [WARN ] io.netty.channel.nio.NioEventLoop -> Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:679)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:472)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
 
[2018-07-07 20:42:19][INFO ] 20:42:19 [WARN ] io.netty.channel.nio.NioEventLoop -> Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
 
[2018-07-07 20:43:03][INFO ] 20:43:00 [WARN ] io.netty.channel.nio.NioEventLoop -> Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded
 
[2018-07-07 20:43:03][INFO ] 20:43:03 [WARN ] io.netty.channel.nio.NioEventLoop -> Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: GC overhead limit exceeded

.....(repeating the same exception)
```

**Comment by HoverEpic** [comment]
pingpassthrough seems having a problem, can you try disable it (just for testing)?
