### ISSUE TITLE
Your school does not have access to this server!

### ISSUE THREAD

**Issue by undeddev** [DragonetMC/DragonProxy#341]
It keeps giving me a school error message for every server i try...

Log;

C:\Users\NO\Documents\Bedrock\DragoNet>java -jar DragonProxy-(1.4.0-1.12.2).jar
[21:42:14][INFO ] This is a development build. It may contain bugs. Do not use on production.
[21:42:14][INFO ] Starting up DragonProxy, version: 0.3.4.5-SNAPSHOT (f0f6553) ...
[21:42:14][INFO ] Supported version of Minecraft PC/Mac: 1.12.2
[21:42:14][INFO ] Supported version of Minecraft: Pocket/Windows 10 Edition: v1.4.0
[21:42:14][INFO ] Java version : 1.8.0_171
[21:42:15][INFO ] System arch : amd64
[21:42:15][INFO ] System os : Windows 10 10.0
[21:42:16][INFO ] Creating thread pool(Size:8)...
[21:42:17][INFO ] 21:42:17 [INFO ] org.pf4j.DefaultPluginStatusProvider -> Enabled plugins: []

[21:42:17][INFO ] 21:42:17 [INFO ] org.pf4j.DefaultPluginStatusProvider -> Disabled plugins: []

[21:42:17][INFO ] 21:42:17 [INFO ] org.pf4j.DefaultPluginManager -> PF4J version 0.0.0 in 'deployment' mode

[21:42:17][INFO ] Loaded sound translates: 499
[21:42:17][INFO ] 21:42:17 [INFO ] org.pf4j.AbstractPluginManager -> No plugins

[21:42:17][INFO ] Binding on :19132 ...
[21:42:18][INFO ] The proxy has started!
Jul 10, 2018 9:42:38 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
Jul 10, 2018 9:42:39 PM org.dragonet.common.utilities.LoginChainDecoder decode
INFO: Failed to verify the integrity of the LoginPacket
java.lang.NullPointerException: No trusted public key found in chain, is the client logged in or cracked
        at org.dragonet.common.utilities.LoginChainDecoder.decode(LoginChainDecoder.java:113)
        at org.dragonet.protocol.packets.LoginPacket.decodePayload(LoginPacket.java:42)
        at org.dragonet.protocol.PEPacket.decode(PEPacket.java:34)
        at org.dragonet.protocol.Protocol.decodeSingle(Protocol.java:142)
        at org.dragonet.protocol.Protocol.decode(Protocol.java:118)
        at org.dragonet.proxy.network.PEPacketProcessor.onTick(PEPacketProcessor.java:98)
        at org.dragonet.proxy.network.UpstreamSession.onTick(UpstreamSession.java:534)
        at org.dragonet.proxy.network.SessionRegister.lambda$onTick$0(SessionRegister.java:35)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at org.dragonet.proxy.network.SessionRegister.onTick(SessionRegister.java:35)
        at org.dragonet.proxy.DragonProxy.onTick(DragonProxy.java:309)
        at org.dragonet.proxy.TickerThread.run(TickerThread.java:32)
com.whirvis.jraknet.session.TimeoutException: Session timeout
        at com.whirvis.jraknet.session.RakNetSession.update(RakNetSession.java:869)
        at com.whirvis.jraknet.server.RakNetServer.start(RakNetServer.java:822)
        at com.whirvis.jraknet.server.RakNetServer$1.run(RakNetServer.java:856)
[21:45:27][INFO ] Client null[/0:0:0:0:0:0:0:1:61891] disconnected! Reason: Client disconnect

**Comment by chuushi** [comment]
Possibilities:

* The IP address the proxy runs on is blacklisted from Mojang's authentication server
* You may need to upgrade to Java 8.

**Comment by ApocalypsjeNL** [comment]
@SimonOrJ No, the IP isn't blocked by mojang. It's because there is no keychain which is provided when you login with a Xbox account. You can disable this by going into the config and set authenticate_players to false.
