### ISSUE TITLE
Client Crash 

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#346]
```
java.lang.NullPointerException
        at org.dragonet.proxy.network.cache.CachedEntity.spawn(CachedEntity.java:162)
        at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:12)
        at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:8)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:163)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:94)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
        at java.lang.Thread.run(Thread.java:748)
[08:58:50][INFO ] Unknown effect ID: 15
[08:58:50][INFO ] Unknown effect ID: 16
```

**Comment by HoverEpic** [comment]
The proxy tried to spawn a non listed player ([CachedEntity.java:162](https://github.com/DragonetMC/DragonProxy/blob/master/proxy/src/main/java/org/dragonet/proxy/network/cache/CachedEntity.java#L162)).
Probably due to a concurrent action.
