### ISSUE TITLE
I can't connect to server

### ISSUE THREAD

**Issue by yurseria** [DragonetMC/DragonProxy#373]
DragonProxy version : 0.3.4.6(dragonproxy-0.3.4.6-SNAPSHOT)
Java edition version : 1.12.2(spigot-1.12.2-R0.1-SNAPSHOT)
Server OS : CentOS 7
Bedrock version : 1.6.1

When I try to connect to the server, the following message is displayed and cannot connect.

`[14:12:26][INFO ] 14:12:26 [WARN ] io.netty.channel.AbstractChannelHandlerContext -> An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.IllegalArgumentException: 0 > -24
        at java.util.Arrays.copyOfRange(Arrays.java:3519)
        at com.whirvis.jraknet.RakNet.splitArray(RakNet.java:640)
        at com.whirvis.jraknet.session.SplitPacket.splitPacket(SplitPacket.java:153)
        at com.whirvis.jraknet.session.RakNetSession.sendMessage(RakNetSession.java:367)
        at com.whirvis.jraknet.session.UnumRakNetPeer.sendMessage(UnumRakNetPeer.java:104)
        at com.whirvis.jraknet.session.RakNetClientSession.handleMessage(RakNetClientSession.java:139)
        at com.whirvis.jraknet.session.RakNetSession.handleMessage0(RakNetSession.java:808)
        at com.whirvis.jraknet.session.RakNetSession.handleEncapsulated(RakNetSession.java:742)
        at com.whirvis.jraknet.session.RakNetSession.handleCustom(RakNetSession.java:572)
        at com.whirvis.jraknet.server.RakNetServer.handleMessage(RakNetServer.java:680)
        at com.whirvis.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:144)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1412)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:943)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by ApocalypsjeNL** [comment]
@Whirvis looks like something with your raknet implementation?

**Comment by MisterSheeple** [comment]
I have the same problem. This worked in 1.5 and 1.4, but not this update.

**Comment by Whirvis** [comment]
This is my bad, apologies. I will get to work on fixing this as soon as possible.

**Comment by whirvis** [comment]
This might be, however I'm not sure. I'm currently working on fixing another issue that is currently present in JRakNet.

**Comment by whirvis** [comment]
I just fixed some other issues in JRakNet, however this does not look like a JRakNet issue in the first place. The error is being triggered by -24 being substituted for the size of an array. I'll need to look where this value is being retrieved.

**Comment by whirvis** [comment]
@yurseria This looks like an error on the decoder's part. Could you please tell me what you did to trigger this so that I can recreate the issue?

**Comment by sudofox** [comment]
I have a similar setup to @yurseria 's and received the same stacktrace.

Bedrock version: freshly downloaded, 1.6.2, on iOS

```
[17:53:55][INFO ] Starting up DragonProxy, version: 0.3.4.6-SNAPSHOT (117df71) ...  
[17:53:55][INFO ] Supported version of Minecraft PC/Mac: 1.12.2 
[17:53:55][INFO ] Supported version of Minecraft: Pocket/Windows 10 Edition: v1.6.0 
[17:53:55][INFO ] Java version : 1.8.0_181 
[17:53:55][INFO ] System arch : amd64 
[17:53:55][INFO ] System os : Linux 3.10.0-862.2.3.el7.x86_64 

-snip, to where I try to connect-

[17:55:56][INFO ] 17:55:56 [WARN ] io.netty.channel.AbstractChannelHandlerContext -> An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.IllegalArgumentException: 0 > -24
	at java.util.Arrays.copyOfRange(Arrays.java:3519)
	at com.whirvis.jraknet.RakNet.splitArray(RakNet.java:640)
	at com.whirvis.jraknet.session.SplitPacket.splitPacket(SplitPacket.java:153)
	at com.whirvis.jraknet.session.RakNetSession.sendMessage(RakNetSession.java:367)
	at com.whirvis.jraknet.session.UnumRakNetPeer.sendMessage(UnumRakNetPeer.java:104)
	at com.whirvis.jraknet.session.RakNetClientSession.handleMessage(RakNetClientSession.java:139)
	at com.whirvis.jraknet.session.RakNetSession.handleMessage0(RakNetSession.java:808)
	at com.whirvis.jraknet.session.RakNetSession.handleEncapsulated(RakNetSession.java:742)
	at com.whirvis.jraknet.session.RakNetSession.handleCustom(RakNetSession.java:572)
	at com.whirvis.jraknet.server.RakNetServer.handleMessage(RakNetServer.java:680)
	at com.whirvis.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1412)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:943)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by whirvis** [comment]
Alright, I'll take a look at it.

**Comment by whirvis** [comment]
For some reason, I am getting no error whatsoever. Instead, the issue I am having can be seen in #374. I've heard that player connections simply don't work at the moment but I could be wrong. I'll ask some of the other devs about that. If that's the case, I'll close #374 with the reasoning that player connections simply arent implemented for 1.13 right now.

I have tested this on my Windows 10 machine (with loopback exemptions enabled through the /loopbackfix command) and on an external Android mobile phone on the same network.

**Comment by Whirvis** [comment]
@sudofox I see you are running 117df71. Could you try and run 673a876-dirty, if possible?

**Comment by whirvis** [comment]
~~@sudofox I'm assuming you have a 1.12 server jar, right? Is it possible you could send that to me? I only have a 1.13 jar which is why I think I'm encountering issue #374 rather than this one (#373)~~

EDIT: I found a 1.12 server jar and even with that I am not encountering this issue. Are you 100% sure you guys are up to date? I suspect you guys might be running an out of date server jar using a bad version of JRakNet.

EDIT #2: I've also noticed that @sudofox is using 1.6.2 on iOS. I know that @yurseria said he is using 1.6.1, but I suspect he might be using an iOS device as well. Maybe this is an issue on behalf of iOS devices? I'll look and see if I can find my iPad and test with that.

**Comment by sudofox** [comment]
Sure thing. I cloned the repo, ran `git checkout 673a876`, built it with `mvn pacakge`, and then tested with both Nintendo Switch (1.6.1) and with iOS (1.6.2), pointed at a PaperSpigot 1.12.2 server.

For both iOS and Nintendo Switch, I got "Could not connect: outdated server!"

The header says "Server by DragonProxy - 1.5.0"

**Comment by whirvis** [comment]
Really? So the error is gone with that version?

**Comment by sudofox** [comment]
Yes, it is gone. This is the output - no errors on console, but ofc my version is too new for the presented server version:

```
[01:12:26][INFO ] Creating thread pool(Size:8)...  
[01:12:27][INFO ] This is a development build. It may contain bugs. Do not use on production. 
[01:12:27][INFO ] ****************************************** 
[01:12:27][INFO ]  
[01:12:27][INFO ] 	You're using autologin, make sure you are the only who can connect on this server ! 
[01:12:27][INFO ]  
[01:12:27][INFO ] ****************************************** 
[01:12:27][INFO ] Starting up DragonProxy, version: 0.3.4.6-SNAPSHOT (673a876) ...  
[01:12:27][INFO ] Supported version of Minecraft PC/Mac: 1.12.2 
[01:12:27][INFO ] Supported version of Minecraft: Pocket/Windows 10 Edition: v1.5.0 
[01:12:27][INFO ] Java version : 1.8.0_181 
[01:12:27][INFO ] System arch : amd64 
[01:12:27][INFO ] System os : Linux 3.10.0-862.2.3.el7.x86_64 
[01:12:27][INFO ] 01:12:27 [INFO ] org.pf4j.DefaultPluginStatusProvider -> Enabled plugins: []
 
[01:12:27][INFO ] 01:12:27 [INFO ] org.pf4j.DefaultPluginStatusProvider -> Disabled plugins: []
 
[01:12:27][INFO ] 01:12:27 [INFO ] org.pf4j.DefaultPluginManager -> PF4J version 0.0.0 in 'deployment' mode
 
[01:12:27][INFO ] Loaded sound translates: 499 
[01:12:27][INFO ] 01:12:27 [INFO ] org.pf4j.AbstractPluginManager -> No plugins
 
[01:12:27][INFO ] Binding on 0.0.0.0:19132 ...  
[01:12:27][INFO ] The proxy has started!  
```

**Comment by whirvis** [comment]
Alright then, I'll close this issue and start working on issue #374 I genuinely think this was just a version using a bad JRakNet version by this point. Does that sound good?

**Comment by sudofox** [comment]
Sure. I can't frankly say I follow what's going on, but I do trust your expertise!

**Comment by whirvis** [comment]
Alright, thanks for being so responsive! Trust me, that makes fixing issues a whole lot easier :D
