### ISSUE TITLE
Can't run DragonProxy on Windows 10 using latest version.

### ISSUE THREAD

**Issue by OnlyBMan** [DragonetMC/DragonProxy#445]
On windows I get no errors, but when launching DragonProxy from a Linux terminal window, I get this

```[19:36:32 ERROR] [com.nukkitx.network.raknet.RakNetServer]: An exception occurred in RakNet
io.netty.channel.ChannelException: getsockopt() failed: Protocol not available
        at io.netty.channel.unix.Socket.recvFromAddress(Native Method) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.unix.Socket.recvFromAddress(Socket.java:209) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:486) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:432) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]```

**Comment by SupremeMortal** [comment]
What's your kernel version? Type `uname -r`

**Comment by OnlyBMan** [comment]
4.4.0-18362-Microsoft

**Comment by Powerlated** [comment]
That's Microsoft's emulated kernel, try running it on real Linux instead. @OnlyBMan
