### ISSUE TITLE
I cant compile and run Dproxy

### ISSUE THREAD

**Issue by Mio-sha512** [DragonetMC/DragonProxy#447]
hi i tried running my newley compiled Dproxy (chrunks branch) and this happend (on wsl)

`
[19:49:49] [main/INFO]: Starting DragonProxy...
[19:49:51] [main/INFO]: Welcome to DragonProxy version 0.0.2-SNAPSHOT
[19:49:51] [main/WARN]: This is a development build. It may contain bugs. Do not use in production.
[19:49:51] [main/ERROR]: A fatal error occurred while initializing the proxy!
java.lang.AssertionError: Static Runtime ID table not found
	at org.dragonet.proxy.util.PaletteManager.loadBlocks(PaletteManager.java:57) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at org.dragonet.proxy.util.PaletteManager.<init>(PaletteManager.java:50) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at org.dragonet.proxy.DragonProxy.initialize(DragonProxy.java:140) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at org.dragonet.proxy.DragonProxy.<init>(DragonProxy.java:111) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at org.dragonet.proxy.Bootstrap.main(Bootstrap.java:53) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
`

and on Windows 10 power shell

`
[19:49:49 INFO]: Starting DragonProxy...
[19:49:51 INFO]: Welcome to DragonProxy version 0.0.2-SNAPSHOT
[19:49:51 WARN]: This is a development build. It may contain bugs. Do not use in production.

`

can someone pls help

**Comment by lukeeey** [comment]
You must clone with the `--recursive` flag
