### ISSUE TITLE
A fatal error occurred while initializing the proxy! 

### ISSUE THREAD

**Issue by xy916** [DragonetMC/DragonProxy#451]
A fatal error occurred while initializing the proxy!
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "remote-servers" (class org.dragonet.proxy.configuration.DragonConfiguration), not marked as ignorable (13 known properties: "motd2", "xbox-auth", "bind-address", "remote-port", "max-players", "remote-address", "remote-auth", "bind-port", "motd", "ping-passthrough", "locale", "fetch-player-skins", "thread-pool-size"])
 at [Source: (FileInputStream); line: 32, column: 4] (through reference chain: org.dragonet.proxy.configuration.DragonConfiguration["remote-servers"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1151) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1545) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at org.dragonet.proxy.DragonProxy.initialize(DragonProxy.java:136) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at org.dragonet.proxy.DragonProxy.<init>(DragonProxy.java:111) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
	at org.dragonet.proxy.Bootstrap.main(Bootstrap.java:53) ~[DragonProxy.jar:0.0.2-SNAPSHOT]

**Comment by lukeeey** [comment]
Dont uncomment that bit, ill fix the error though
