### ISSUE TITLE
RakNet No PacketCodec exception when connecting

### ISSUE THREAD

**Issue by philr-biz** [DragonetMC/DragonProxy#453]
I'm running the latest official (1.14.4) Java-edition server from [here](https://www.minecraft.net/en-us/download/server/) on a Windows 10 machine. I'm using the JDK only (no JRE installed).

I've re-instated the server completely to confirm it's nothing to do with world save or server configuration - I can join from Java edition and everything works as expected.

When I try to join from Minecraft Bedrock from iOS (latest 1.13) I can see the server and the MOTD is displayed correctly.

When I try to connect the proxy generates the following error:
`C:\Users\Phil\Documents\DragonProxy\snapshots\251>java -Xlog:all=debug:file=proxy.log -jar DragonProxy.jar
[12:46:14 INFO]: Starting DragonProxy...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[12:46:22 INFO]: Welcome to DragonProxy version 0.0.2-SNAPSHOT
[12:46:22 WARN]: This is a development build. It may contain bugs. Do not use in production.
[12:46:29 INFO]: Ping passthrough enabled
[12:46:35 INFO]: RakNet server started on 0.0.0.0
[12:46:35 INFO]: Done (13.74s)!
[12:47:35 ERROR] [com.nukkitx.network.raknet.RakNetServer]: An exception occurred in RakNet
java.lang.IllegalStateException: No PacketCodec is set!
        at com.nukkitx.network.util.Preconditions.checkState(Preconditions.java:497) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockSession.checkPacket(BedrockSession.java:97) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockSession.sendPacketImmediately(BedrockSession.java:83) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockServerSession.disconnect(BedrockServerSession.java:33) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockServerSession.disconnect(BedrockServerSession.java:17) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at org.dragonet.proxy.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:78) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:15) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:22) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:315) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:442) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:420) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:408) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:287) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:278) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

Following this the proxy has to be restarted, however the server is still running correctly, and can be accessed from Java Edition as normal.

While this occurs "out-of-the-box" I have also had the same error with Xlog:all=debug set and some large log files - let me know if and where you'd like these uploading.

**Comment by philr-biz** [comment]
Looks like I am not alone with this, here's a pastebin from someone else with the same error: https://pastebin.com/ztf0EeP0

**Comment by Redned235** [comment]
Most likely because DP does not support 1.13 bedrock yet.

**Comment by philr-biz** [comment]
> Most likely because DP does not support 1.13 bedrock yet.

Darn - wish I hadn't update the app then!

**Comment by Heath123** [comment]
It's not worth it. This is nowhere near ready.
