### ISSUE TITLE
When player joins it crashes - No PacketCodec is set!

### ISSUE THREAD

**Issue by FFrozTT** [DragonetMC/DragonProxy#456]
As soon as a player joins it crashes:

```
[22:04:03 ERROR] [com.nukkitx.network.raknet.RakNetServer]: An exception occurred in RakNet
java.lang.IllegalStateException: No PacketCodec is set!
        at com.nukkitx.network.util.Preconditions.checkState(Preconditions.java:497) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockSession.checkPacket(BedrockSession.java:97) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockSession.sendPacketImmediately(BedrockSession.java:83) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockServerSession.disconnect(BedrockServerSession.java:33) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockServerSession.disconnect(BedrockServerSession.java:17) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at org.dragonet.proxy.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:68) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:15) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:22) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:301) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:428) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:406) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:394) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:273) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:547) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:382) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:331) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[DragonProxy.jar:0.0.2-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

```

**Comment by lukeeey** [comment]
It doesnt currently support 1.13

**Comment by FFrozTT** [comment]
I tried a 1.12 APK but it gives this error now:
`Player  disconnected from remote. Reason: Login failed: Authentication error: Access Token can not be null or empty.`

I'm not trying to do any auth because this is just a local server I'm hosting on same box as proxy so I have it set to offline.

**Comment by FFrozTT** [comment]
Even when I set it to credentials (which I don't want auth) I get about 5 seconds of clouds then it times out:
`[01:52:01 INFO]: Player  disconnected from remote. Reason: disconnect.timeout`

**Comment by FFrozTT** [comment]
I keep trying different version to no avail. Currently I'm using Bedrock v1.12.0 client, Java v1.12.0 Server but client keep disconnecting with message:
`Player  disconnected from remote. Reason: multiplayer.disconnect.outdated_server`
I've tried other versions like 1.12.1 as well with same results. Why would client complain like this when server is the same version.  What are the supported client/server versions for this to work?

**Comment by Redned235** [comment]
> I keep trying different version to no avail. Currently I'm using Bedrock v1.12.0 client, Java v1.12.0 Server but client keep disconnecting with message:
> `Player disconnected from remote. Reason: multiplayer.disconnect.outdated_server`
> I've tried other versions like 1.12.1 as well with same results. Why would client complain like this when server is the same version. What are the supported client/server versions for this to work?

Java 1.14 and Bedrock 1.12. It’s stated on the README as well.

**Comment by FFrozTT** [comment]
Tried that, then it disconnects and says Timed Out

**Comment by applebee1558** [comment]
well, this is disturbing as there is no way you can downgrade the iOS or Windows 10 MCPE clients back to 1.12, so guess I will just have to wait until it gets fixed.

**Comment by exabrial** [comment]
Just letting you know I'm seeing this bug too with 1.13.

Thank you very much for putting your free time into working on this project. One of my buddies' daughters is obsessed with Minecraft, this allows them to play together using the devices they have and can spend quality time together. :) Your efforts are always much appreciated .

Also, I'm a "Java guy", so if there is any sort of debugging or dumps you need, I'd be glad to assist

**Comment by applebee1558** [comment]
Why close this issue if there hasn't been any PR or commits that solve it?

**Comment by lukeeey** [comment]
Are you blind

**Comment by applebee1558** [comment]
sorry, legit didn't see that, maby my github glitched

**Comment by lukeeey** [comment]
No problem

**Comment by exabrial** [comment]
lukeeey thanks a ton! I'll have my buddy give it a try
