### ISSUE TITLE
Invalid legacy skin

### ISSUE THREAD

**Issue by Mason10198** [DragonetMC/DragonProxy#472]
Running the latest proxy build from Jenkins on Win10, I try and join locally from PE. It appears to login, and leaves me (the player) floating in empty space. I check the console and I see the following, which happens every time I attempt:

```
[16:12:19] [Network Listener - #1/ERROR]: An exception occurred in RakNet
java.lang.IllegalArgumentException: Invalid legacy skin
	at com.nukkitx.protocol.bedrock.data.ImageData.checkLegacySkinSize(ImageData.java:52) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.protocol.bedrock.data.SerializedSkin.of(SerializedSkin.java:33) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at org.dragonet.proxy.network.session.ProxySession.spawn(ProxySession.java:295) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at org.dragonet.proxy.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:198) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.protocol.bedrock.packet.SetLocalPlayerAsInitializedPacket.handle(SetLocalPlayerAsInitializedPacket.java:13) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:22) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:301) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:428) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:406) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:399) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:273) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

**Comment by lukeeey** [comment]
Are you wearing a cape? If not, can you please send me your skin?

**Comment by Mason10198** [comment]
[My skin](https://minecraft.tools/en/skin.php?skin=mason10198)
No cape.  The same error occurs whether `fetch-player-skins: true` or `fetch-player-skins: false`.

**Comment by lukeeey** [comment]
I'm getting no issues on 1.14.30, but try the latest build anyway

**Comment by lukeeey** [comment]
Just updated it again but i have no way to know if it works as it doesnt affect me

**Comment by Mason10198** [comment]
I figured it out. Minecraft PE has a new "Character Creator" which was being used as default skin on my device and causing issues. I downloaded my skin as a PNG and imported it into MCPE and that allowed me to login.

However, MCPE is now crashing about 1 second after every successful login.

**Comment by Mason10198** [comment]
Here is the log from that:

```
[16:59:00] [Network Listener - #1/INFO]: Mason10198 connected
[16:59:01] [Network Listener - #1/INFO]: Mason10198 connected
[16:59:03] [Network Listener - #1/WARN]: SPAWN PLAYER
[16:59:27] [nioEventLoopGroup-12-1/INFO]: Player connected to remote mason10198.my.pebble.host
[16:59:27] [pool-2-thread-2/INFO]: Player Mason10198 has been authenticated
[16:59:28] [Thread-14/INFO]: (debug) Unhandled entity status: PLAYER_DISABLE_REDUCED_DEBUG
[16:59:28] [Thread-14/INFO]: (debug) Unhandled entity status: PLAYER_OP_PERMISSION_LEVEL_4
[16:59:28] [Thread-14/INFO]: Spawned player mason10198 at -256.56462859365297 54.0 -10.002068500892737
[16:59:28] [Thread-14/INFO]: {x=IntTag(x) { -401 }, y=IntTag(y) { 21 }, z=IntTag(z) { 23 }, id=StringTag(id) { minecraft:chest }}
[16:59:28] [Thread-14/INFO]: {x=IntTag(x) { -401 }, y=IntTag(y) { 21 }, z=IntTag(z) { 29 }, id=StringTag(id) { minecraft:chest }}
[16:59:28] [Thread-14/INFO]: {MaxNearbyEntities=ShortTag(MaxNearbyEntities) { 6 }, RequiredPlayerRange=ShortTag(RequiredPlayerRange) { 16 }, SpawnCount=ShortTag(SpawnCount) { 4 }, SpawnData=CompoundTag(SpawnData) { {id=StringTag(id) { minecraft:zombie }} }, MaxSpawnDelay=ShortTag(MaxSpawnDelay) { 800 }, Delay=ShortTag(Delay) { 20 }, x=IntTag(x) { -400 }, y=IntTag(y) { 21 }, z=IntTag(z) { 26 }, id=StringTag(id) { minecraft:mob_spawner }, SpawnRange=ShortTag(SpawnRange) { 4 }, MinSpawnDelay=ShortTag(MinSpawnDelay) { 200 }}
[16:59:28] [Thread-14/INFO]: {x=IntTag(x) { -398 }, y=IntTag(y) { 21 }, z=IntTag(z) { 31 }, id=StringTag(id) { minecraft:chest }}
[16:59:28] [Thread-14/INFO]: {x=IntTag(x) { -395 }, y=IntTag(y) { 21 }, z=IntTag(z) { 29 }, id=StringTag(id) { minecraft:chest }}
[16:59:28] [Thread-14/INFO]: {MaxNearbyEntities=ShortTag(MaxNearbyEntities) { 6 }, RequiredPlayerRange=ShortTag(RequiredPlayerRange) { 16 }, SpawnCount=ShortTag(SpawnCount) { 4 }, SpawnData=CompoundTag(SpawnData) { {id=StringTag(id) { minecraft:skeleton }} }, MaxSpawnDelay=ShortTag(MaxSpawnDelay) { 800 }, Delay=ShortTag(Delay) { 20 }, x=IntTag(x) { -395 }, y=IntTag(y) { 21 }, z=IntTag(z) { 31 }, id=StringTag(id) { minecraft:mob_spawner }, SpawnRange=ShortTag(SpawnRange) { 4 }, MinSpawnDelay=ShortTag(MinSpawnDelay) { 200 }}
[16:59:28] [Thread-14/INFO]: {MaxNearbyEntities=ShortTag(MaxNearbyEntities) { 6 }, RequiredPlayerRange=ShortTag(RequiredPlayerRange) { 16 }, SpawnCount=ShortTag(SpawnCount) { 4 }, SpawnData=CompoundTag(SpawnData) { {id=StringTag(id) { minecraft:zombie }} }, MaxSpawnDelay=ShortTag(MaxSpawnDelay) { 800 }, Delay=ShortTag(Delay) { 20 }, x=IntTag(x) { -372 }, y=IntTag(y) { 18 }, z=IntTag(z) { -3 }, id=StringTag(id) { minecraft:mob_spawner }, SpawnRange=ShortTag(SpawnRange) { 4 }, MinSpawnDelay=ShortTag(MinSpawnDelay) { 200 }}
[16:59:28] [Thread-14/INFO]: {x=IntTag(x) { -370 }, y=IntTag(y) { 18 }, z=IntTag(z) { -6 }, id=StringTag(id) { minecraft:chest }}
[16:59:28] [Thread-14/INFO]: {x=IntTag(x) { -375 }, y=IntTag(y) { 18 }, z=IntTag(z) { -2 }, id=StringTag(id) { minecraft:chest }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -299 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 53 }, Text3=StringTag(Text3) { {"text":""} }, z=IntTag(z) { -158 }, Text2=StringTag(Text2) { {"extra":[{"text":"Verser"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -299 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"text":""} }, z=IntTag(z) { -127 }, Text2=StringTag(Text2) { {"extra":[{"text":"JPAC"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -299 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 53 }, Text3=StringTag(Text3) { {"text":""} }, z=IntTag(z) { -51 }, Text2=StringTag(Text2) { {"extra":[{"text":"Jones"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -300 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 52 }, Text3=StringTag(Text3) { {"text":""} }, z=IntTag(z) { -6 }, Text2=StringTag(Text2) { {"extra":[{"text":"Moses-Provine"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -293 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 52 }, Text3=StringTag(Text3) { {"text":""} }, z=IntTag(z) { 24 }, Text2=StringTag(Text2) { {"extra":[{"text":"Anthony"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -263 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"text":""} }, z=IntTag(z) { -122 }, Text2=StringTag(Text2) { {"extra":[{"text":"Cone Bottoms"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -261 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 55 }, Text3=StringTag(Text3) { {"text":""} }, z=IntTag(z) { -84 }, Text2=StringTag(Text2) { {"extra":[{"text":"Berry Chapel"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -262 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"text":""} }, z=IntTag(z) { -58 }, Text2=StringTag(Text2) { {"extra":[{"text":"Berry Bible"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {MaxNearbyEntities=ShortTag(MaxNearbyEntities) { 6 }, RequiredPlayerRange=ShortTag(RequiredPlayerRange) { 16 }, SpawnCount=ShortTag(SpawnCount) { 4 }, SpawnData=CompoundTag(SpawnData) { {id=StringTag(id) { minecraft:spider }} }, MaxSpawnDelay=ShortTag(MaxSpawnDelay) { 800 }, Delay=ShortTag(Delay) { 20 }, x=IntTag(x) { -246 }, y=IntTag(y) { 43 }, z=IntTag(z) { -140 }, id=StringTag(id) { minecraft:mob_spawner }, SpawnRange=ShortTag(SpawnRange) { 4 }, MinSpawnDelay=ShortTag(MinSpawnDelay) { 200 }}
[16:59:28] [Thread-14/INFO]: {x=IntTag(x) { -249 }, y=IntTag(y) { 43 }, z=IntTag(z) { -138 }, id=StringTag(id) { minecraft:chest }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -255 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"extra":[{"text":"mason10198"}],"text":""} }, z=IntTag(z) { -12 }, Text2=StringTag(Text2) { {"extra":[{"text":"TheDelph v0.1"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -255 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"extra":[{"text":"<-----"}],"text":""} }, z=IntTag(z) { -13 }, Text2=StringTag(Text2) { {"extra":[{"text":"Flippen-Perrin"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -256 }, Text4=StringTag(Text4) { {"extra":[{"text":"OBU as possible!"}],"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"extra":[{"text":"accurate to the real"}],"text":""} }, z=IntTag(z) { -15 }, Text2=StringTag(Text2) { {"extra":[{"text":"project is to be as"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"extra":[{"text":"The goal of this"}],"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -255 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"extra":[{"text":"----->"}],"text":""} }, z=IntTag(z) { -8 }, Text2=StringTag(Text2) { {"extra":[{"text":"Anthony"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -255 }, Text4=StringTag(Text4) { {"extra":[{"text":"an administrator"}],"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"extra":[{"text":"on this map by"}],"text":""} }, z=IntTag(z) { -9 }, Text2=StringTag(Text2) { {"extra":[{"text":"permissions to build"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"extra":[{"text":"You must be given"}],"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -255 }, Text4=StringTag(Text4) { {"extra":[{"text":"NASA satellite data"}],"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"extra":[{"text":"from real-world"}],"text":""} }, z=IntTag(z) { -10 }, Text2=StringTag(Text2) { {"extra":[{"text":"map was compiled"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"extra":[{"text":"The terrain in this"}],"text":""} }}
[16:59:28] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -255 }, Text4=StringTag(Text4) { {"extra":[{"text":"Arkadelphia, AR"}],"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"extra":[{"text":"University"}],"text":""} }, z=IntTag(z) { -11 }, Text2=StringTag(Text2) { {"extra":[{"text":"Ouachita Baptist"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"extra":[{"text":"Welcome to"}],"text":""} }}
[16:59:29] [Thread-14/INFO]: {Color=StringTag(Color) { black }, x=IntTag(x) { -192 }, Text4=StringTag(Text4) { {"text":""} }, y=IntTag(y) { 54 }, Text3=StringTag(Text3) { {"text":""} }, z=IntTag(z) { -49 }, Text2=StringTag(Text2) { {"extra":[{"text":"Library"}],"text":""} }, id=StringTag(id) { minecraft:sign }, Text1=StringTag(Text1) { {"text":""} }}
[16:59:29] [Thread-14/INFO]: (debug) SetSlotTranslator: Window not in cache, id: 255
[16:59:29] [Thread-14/INFO]: {x=IntTag(x) { -419 }, y=IntTag(y) { 36 }, z=IntTag(z) { -140 }, id=StringTag(id) { minecraft:chest }}
[16:59:29] [Thread-14/INFO]: {x=IntTag(x) { -418 }, y=IntTag(y) { 36 }, z=IntTag(z) { -140 }, id=StringTag(id) { minecraft:chest }}
[16:59:29] [Thread-14/INFO]: {MaxNearbyEntities=ShortTag(MaxNearbyEntities) { 6 }, RequiredPlayerRange=ShortTag(RequiredPlayerRange) { 16 }, SpawnCount=ShortTag(SpawnCount) { 4 }, SpawnData=CompoundTag(SpawnData) { {id=StringTag(id) { minecraft:spider }} }, MaxSpawnDelay=ShortTag(MaxSpawnDelay) { 800 }, Delay=ShortTag(Delay) { 20 }, x=IntTag(x) { -417 }, y=IntTag(y) { 36 }, z=IntTag(z) { -139 }, id=StringTag(id) { minecraft:mob_spawner }, SpawnRange=ShortTag(SpawnRange) { 4 }, MinSpawnDelay=ShortTag(MinSpawnDelay) { 200 }}
[17:00:00] [nioEventLoopGroup-12-1/INFO]: Player disconnected from remote. Reason: TIMED_OUT
```

**Comment by lukeeey** [comment]
I fixed that in the latest commit
