### ISSUE TITLE
Add better usage/setup instructions

### ISSUE THREAD

**Issue by inxomnyaa** [DragonetMC/DragonProxy#48]
I really struggle to use it on my windows pc. The Readme is useless, the forum too.

Maybe we can also discuss my problem here:

When i set up DragonProxy on the same device like my Minecraft windows 10 edition, i see "DragonProxy - 1.0" in the server list.
![image](https://cloud.githubusercontent.com/assets/8733998/23170530/c2c9d3b0-f84f-11e6-9e91-b3607db4f50d.png)

the config: redirects to wolvesfortress.de:25566, my spigot test server.

When i join, i simply get 
![image](https://cloud.githubusercontent.com/assets/8733998/23170522/bc174fb6-f84f-11e6-84b6-89ce9c20ffbb.png)

When i set up DragonProxy on the remote server, config going to "localhost:25565", and i am trying to find that port from my client, it won't show up, neither let me connect.

Dragonproxy on client & dragonproxy on server doesn't change a thing too.

**Comment by DaMatrix** [comment]
Most of DragonProxy doesn't work at all yet, so don't expect it to.

**Comment by inxomnyaa** [comment]
In the other issues i read its working, except for chunks missing

**Comment by inxomnyaa** [comment]
Just figured out that i see stuff when starting it with powershell -.-

```[16:25:23] [INFO] [PE Clientside] Client /192.168.5.62:57361 about to connect
[16:25:23] [INFO] [PE Clientside] Client Connected: /192.168.5.62:57361
java.lang.NegativeArraySizeException
        at sul.utils.Buffer.readBytes(Buffer.java:27)
        at org.dragonet.proxy.utilities.LoginPacketPayload.decodeChainData(LoginPacketPayload.java:74)
        at org.dragonet.proxy.utilities.LoginPacketPayload.decode(LoginPacketPayload.java:68)
        at org.dragonet.proxy.network.adapter.MCPEClientProtocolAdapter.onClientLoginRequest(MCPEClientProtocolAdapter.java:108)
        at org.dragonet.proxy.network.adapter.MCPEClientProtocolAdapter.handlePacket(MCPEClientProtocolAdapter.java:290)
        at org.dragonet.proxy.network.adapter.MCPEClientProtocolAdapter.handlePacket(MCPEClientProtocolAdapter.java:353)
        at net.marfgamer.jraknet.session.RakNetClientSession.handlePacket(RakNetClientSession.java:153)
        at net.marfgamer.jraknet.session.RakNetSession.handlePacket0(RakNetSession.java:706)
        at net.marfgamer.jraknet.session.RakNetSession.handleEncapsulated(RakNetSession.java:641)
        at net.marfgamer.jraknet.session.RakNetSession.handleCustom(RakNetSession.java:517)
        at net.marfgamer.jraknet.server.RakNetServer.handlePacket(RakNetServer.java:592)
        at net.marfgamer.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:117)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Unknown Source)
[16:25:23] [INFO] [PE to PC] <<< sul.protocol.pocket101.play.Login```

**Comment by inxomnyaa** [comment]
And on target server:
```PS C:\Users\Administrator\Desktop\DragonProxy-refactor\DragonProxy\target> java -jar .\dragonproxy.jar
>←[36;1m[16:32:20] ←[33;1m[WARNING] ←[33;1mThis is a development build. It may contain bugs. Do not use on production.
←[37;1m←[0m
←[36;1m[16:32:20] ←[0m[INFO] Starting up DragonProxy, version: 0.0.7 ... ←[37;1m←[0m
←[36;1m[16:32:20] ←[0m[INFO] Supported version of Minecraft PC/Mac: 1.11.2←[37;1m←[0m
←[36;1m[16:32:20] ←[0m[INFO] Supported version of Minecraft: Pocket/Windows 10 Edition: 1.0.2←[37;1m←[0m
←[36;1m[16:32:20] ←[0m[INFO] Creating thread pool(Size:0)... ←[37;1m←[0m
←[36;1m[16:32:20] ←[0m[INFO] Starting up the Minecraft PE ClientProtocolAdapter←[37;1m←[0m
←[36;1m[16:32:20] ←[0m[INFO] Binding on 0.0.0.0:19132 ... ←[37;1m←[0m
←[36;1m[16:32:20] ←[0m[INFO] The proxy has started! ←[37;1m←[0m
←[36;1m[16:32:20] ←[0m[INFO] [PE Clientside] Listening for PE connections←[37;1m←[0m
←[36;1m[16:32:20] ←[31;1m[SEVERE] [PE Clientside] An unhandled exception has occured with the session: /45.79.134.18:555
39←[37;1m←[0m
java.lang.IndexOutOfBoundsException: readerIndex(20) + length(1) exceeds writerIndex(20): UnpooledUnsafeHeapByteBuf(ridx
: 20, widx: 20, cap: 20)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1413)
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
        at net.marfgamer.jraknet.Packet.read(Packet.java:107)
        at net.marfgamer.jraknet.Packet.checkMagic(Packet.java:288)
        at net.marfgamer.jraknet.protocol.status.UnconnectedPing.decode(UnconnectedPing.java:64)
        at net.marfgamer.jraknet.server.RakNetServer.handlePacket(RakNetServer.java:486)
        at net.marfgamer.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:117)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Unknown Source)
←[36;1m[16:32:20] ←[0m[INFO] [PE Clientside] Client /212.204.61.34:57361 about to connect←[37;1m←[0m
←[36;1m[16:32:20] ←[0m[INFO] [PE Clientside] Client Connected: /212.204.61.34:57361←[37;1m←[0m
java.lang.NegativeArraySizeException
        at sul.utils.Buffer.readBytes(Buffer.java:27)
        at org.dragonet.proxy.utilities.LoginPacketPayload.decodeChainData(LoginPacketPayload.java:74)
        at org.dragonet.proxy.utilities.LoginPacketPayload.decode(LoginPacketPayload.java:68)
        at org.dragonet.proxy.network.adapter.MCPEClientProtocolAdapter.onClientLoginRequest(MCPEClientProtocolAdapter.j
ava:108)
        at org.dragonet.proxy.network.adapter.MCPEClientProtocolAdapter.handlePacket(MCPEClientProtocolAdapter.java:290)

        at org.dragonet.proxy.network.adapter.MCPEClientProtocolAdapter.handlePacket(MCPEClientProtocolAdapter.java:353)

        at net.marfgamer.jraknet.session.RakNetClientSession.handlePacket(RakNetClientSession.java:153)
        at net.marfgamer.jraknet.session.RakNetSession.handlePacket0(RakNetSession.java:706)
        at net.marfgamer.jraknet.session.RakNetSession.handleEncapsulated(RakNetSession.java:641)
        at net.marfgamer.jraknet.session.RakNetSession.handleCustom(RakNetSession.java:517)
        at net.marfgamer.jraknet.server.RakNetServer.handlePacket(RakNetServer.java:592)
        at net.marfgamer.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:117)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Unknown Source)
←[36;1m[16:32:20] ←[0m[INFO] [PE to PC] <<< sul.protocol.pocket101.play.Login←[37;1m←[0m

```

**Comment by TheDiamondYT1** [comment]
How come your command prompt isint showing the colours?

**Comment by inxomnyaa** [comment]
Blame Windows server 2012 R2

**Comment by DaMatrix** [comment]
@thebigsmileXD well even despite that, i can login fine, just there's nothing to see other than chat. and no, it's not that we "just need to get chunks working". once we get chunks working we can start working on everything else.

**Comment by inxomnyaa** [comment]
@DaMatrix are you using 1.0.3, Windows 10 edition or MCPE?

**Comment by DaMatrix** [comment]
i've used 1.0.3 on android and mcpelauncher-linux. also why the thumbs-down?

**Comment by whirvis** [comment]
As the creator of JRakNet I just want to say JRakNet now has a maven repository and is now on version 2.5.1, which has fixed a major bug preventing split packets from being sent correctly. Also, always be on the lookout for updates as if I ever find a bug I fix it and push a new update as soon as possible Later today I plan to release version 2.5.2 which will add support for handling and sending raw data packets with the server and client, making the UT3 Query Protocol possible to implement :)

Simply go [here](http://github.com/JRakNet/JRakNet) for info how to use the maven repository

**Comment by MrPowerGamerBR** [comment]
Can confirm that JRakNet is now "usable" for Minecraft Pocket Edition servers.

My Nukkit fork (shameless plug https://github.com/PocketDreams/SequinLand ) uses JRakNet instead of Nukkit's buggy RakNet and it works perfectly, even better than Nukkit's RakNet!

**Comment by DaMatrix** [comment]
@MarfGamer #49 :D

**Comment by whirvis** [comment]
@DaMatrix I have updated JRakNet to version [v2.6.1](https://github.com/JRakNet/JRakNet/releases/tag/v2.6.1) which adds some useful features that are needed to implement the UT3 Query protocol :) If possible, I suggest you update the fork

**Comment by inxomnyaa** [comment]
It should be a submodule.

**Comment by DaMatrix** [comment]
No, it should not. We're developing DragonProxy, net jRakNet, and therefore people should not have to compile JRakNet to build the project.

**Comment by inxomnyaa** [comment]
I thought for git-clone purposes.

**Comment by DaMatrix** [comment]
?

**Comment by whirvis** [comment]
R.I.P.
