### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by MaxwellRU** [DragonetMC/DragonProxy#486]
First login to Java server is ok - 60 fps at hub (lobby).
Walk into teleport and game crashes.

Now, when I log into server - my game crashes every time.

**Comment by MVDW-Java** [comment]
My client also crashes.. but its just when I login into my server. and not teleporting.
I thinks its something in the world that dragon can't handle propperly. 🤔 

Edit: I've Updated the Proxy and it does not crash anymore.

**Comment by videosambo** [comment]
Same problem here, using latest stable build, waterfall version is latest and lobby world is paper 1.12 with viaversion

**Comment by lukeeey** [comment]
Does it still happen with the latest build?

**Comment by Shock95** [comment]
Yes

**Comment by bc1bb** [comment]
I have the same problem and I get this error:
```
[02:57:14 INFO]: Cached entity (mob) already exists, cant spawn a new one: PLAYER
[02:57:14 INFO]: (debug) Player action not successful: START_DIGGING
[02:57:14 ERROR]: Throwing
java.lang.NullPointerException: null
	at org.dragonet.proxy.util.BlockUtils.isCorrectTool(BlockUtils.java:34) ~[dragonproxy-0.4-pre1.jar:0.4-SNAPSHOT]
	at org.dragonet.proxy.util.BlockUtils.getBreakTime(BlockUtils.java:66) ~[dragonproxy-0.4-pre1.jar:0.4-SNAPSHOT]
	at org.dragonet.proxy.network.translator.java.player.PCPlayerActionAckTranslator.translate(PCPlayerActionAckTranslator.java:49) ~[dragonproxy-0.4-pre1.jar:0.4-SNAPSHOT]
	at org.dragonet.proxy.network.translator.java.player.PCPlayerActionAckTranslator.translate(PCPlayerActionAckTranslator.java:33) ~[dragonproxy-0.4-pre1.jar:0.4-SNAPSHOT]
	at org.dragonet.proxy.network.translator.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:69) ~[dragonproxy-0.4-pre1.jar:0.4-SNAPSHOT]
	at org.dragonet.proxy.network.session.ProxySession$1.packetReceived(ProxySession.java:157) ~[dragonproxy-0.4-pre1.jar:0.4-SNAPSHOT]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[dragonproxy-0.4-pre1.jar:0.4-SNAPSHOT]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:148) ~[dragonproxy-0.4-pre1.jar:0.4-SNAPSHOT]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:323) ~[dragonproxy-0.4-pre1.jar:0.4-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

```

(Server is running on the same machine, Spigot 1.15.2 on Debian 10)

**Comment by lukeeey** [comment]
What block were you mining and with what item @jusdepatate

**Comment by bc1bb** [comment]
> What block were you mining and with what item @jusdepatate

@lukeeey, My tester wasn't mining anything, the map wasn't even loaded, he crashed when the server tried to proxy him

**Comment by lukeeey** [comment]
He mined something (or started mining it) - even holding down on the block (if on touch screen) will cause it to tell the server it’s started digging - as it says in the log that he started digging

**Comment by bc1bb** [comment]
> He mined something (or started mining it) - even holding down on the block (if on touch screen) will cause it to tell the server it’s started digging - as it says in the log that he started digging

Anyways, I still get this error when he tries to connect:
```
[02:57:14 INFO]: Cached entity (mob) already exists, cant spawn a new one: PLAYER
```

**Comment by lukeeey** [comment]
Not an error, but I’m not sure what that is. There is already a seperate packet for spawning players so I don’t see why MobType.PLAYER even exists

**Comment by videosambo** [comment]
I think this has something to do with world.

**Comment by james090500** [comment]
This original issue is fixed. If you have further issues please make a new issue.
