### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by nixerg** [DragonetMC/DragonProxy#492]
Hi, 
Compiled spigot server version 1.14.3 (as I have a client version 1.14.3 on my Samsung pad).
Downloaded the latest proxy (version 0.4).
Switched off Defender and Firewall on my windows 8.1 pc.
Started both the server and the proxy. So far so good.

Added server in the client - my pc address, port 19132.
Client found it (but shown server 1.14.0 (not 1.14.3), is it bad?)

Then it connected for a couple of seconds, I saw the sky.
The proxy said that Steve is connected. The server said nothing.
And then I got "An established connection was aborted by the software in your host machine".
I tried to connect again and got another error: Server outdated! I'm still on 1.14.3.
And all the following tries ended with the same error - server outdated.
Proxies log has a null exception before the error.

Here are some lines from the log:
[12:25:09] [Network Listener - #1/INFO]: Steve connected
[12:26:04] [Network Listener - #1/WARN]: SPAWN PLAYER
[12:26:07] [nioEventLoopGroup-29-1/INFO]: Player connected to remote 127.0.0.1
[12:26:07] [nioEventLoopGroup-29-1/INFO]: Player disconnected from remote. Reason: java.io.IOException: An established connection was aborted by the software in your host machine
[12:27:39] [Network Listener - #1/INFO]: Steve connected
[12:28:33] [Network Listener - #1/WARN]: SPAWN PLAYER
[12:28:36] [nioEventLoopGroup-45-1/INFO]: Player connected to remote 127.0.0.1
[12:28:36] [nioEventLoopGroup-45-1/ERROR]: Throwing
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Matcher.reset(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Matcher.<init>(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern.matcher(Unknown Source) ~[?:1.8.0_241]
	at java.util.Formatter.parse(Unknown Source) ~[?:1.8.0_241]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_241]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_241]
	at java.lang.String.format(Unknown Source) ~[?:1.8.0_241]
	at org.dragonet.proxy.configuration.lang.MinecraftLanguage.translate(MinecraftLanguage.java:61) ~[DragonProxy.jar:0.4-SNAPSHOT]
	at org.dragonet.proxy.network.translator.misc.MessageTranslator.translate(MessageTranslator.java:108) ~[DragonProxy.jar:0.4-SNAPSHOT]
... (many)
[12:28:36] [nioEventLoopGroup-45-1/INFO]: Player disconnected from remote. Reason: Outdated server! I'm still on 1.14.3

The server has no new logs after it is started.

What am I doing wrong?

**Comment by james090500** [comment]
Bedrock and spigot versions are completely different. You need to use the latest spigot version to be able to connect.

**Comment by nixerg** [comment]
Oh, I see, I will try that, thanks

**Comment by nixerg** [comment]
Hmm, did I understood correctly that there should be a Minecraft PE Spigot version? 
To connect to the Spigot server.

**Comment by james090500** [comment]
No. You connect to DragonProxy which then forwards your connection to any java server which must support version of 1.15.2.

Similar to how you have it setup. However, the remote-server must be 1.15.2

**Comment by nixerg** [comment]
Ok. It works, thanks a lot.
