### ISSUE TITLE
No connect to MCPE

### ISSUE THREAD

**Issue by Encritary** [DragonetMC/DragonProxy#5]
It doesn't connect to mcpe servers, only to PC

**Comment by TheDiamondYT1** [comment]
I know blame @DefinitlyEvil

**Comment by Encritary** [comment]
@TheDiamondYT1 so, it will be fixed in near update?

**Comment by Encritary** [comment]
Because, iTXTech's proxys is very buggy, I want to use something like BungeeCord

**Comment by Rouvas** [comment]
Log when you come to the server

`[11:28:52] [INFO] [MrSN] Connecting to remote pocket server at [91.121.50.41:19132]
[11:28:52] [INFO] [DEBUG] Client connecting, PLOAD=1447, TRIES=4
[11:28:52] [INFO] [DEBUG] Trying to connect, TRY=0...
[11:28:52] [INFO] [DEBUG] Recieved OPEN_CONNECTION_REPLY_1 (@ Connection.java:484)
[11:28:52] [INFO] [DEBUG] Sending to remote OPEN_CONNECTION_REQUEST_2 (@Connection.java:223)
[11:28:52] [INFO] [DEBUG] Sending to remote DATA_PACKET_4 (@Connection.java:223)
[11:28:53] [INFO] [DEBUG] Recieved OPEN_CONNECTION_REPLY_2 (@ Connection.java:484)
[11:28:53] [INFO] [DEBUG] Sending to remote DATA_PACKET_0 (@Connection.java:223)
[11:28:53] [INFO] [DEBUG] Sending to remote DATA_PACKET_4 (@Connection.java:223)
[11:28:53] [INFO] [DEBUG] Recieved ACK (@ Connection.java:484)
[11:28:53] [INFO] [DEBUG] Recieved DATA_PACKET_0 (@ Connection.java:484)
[11:28:53] [INFO] Recieved encapulated packet INDEX=null
**[11:28:53] [WARNING] java.lang.NullPointerException
[11:28:53] [WARNING]    at org.dragonet.raknet.client.Connection.handleEncapsulatedPacket(Connection.java:367)
[11:28:53] [WARNING]    at org.dragonet.raknet.client.Connection.handlePacket(Connection.java:519)
[11:28:53] [WARNING]    at org.dragonet.raknet.client.ConnectionManager.receivePacket(ConnectionManager.java:160)
[11:28:53] [WARNING]    at org.dragonet.raknet.client.ConnectionManager.tickProcessor(ConnectionManager.java:121)
[11:28:53] [WARNING]    at org.dragonet.raknet.client.ConnectionManager.run(ConnectionManager.java:109)
[11:28:53] [WARNING]    at org.dragonet.raknet.client.ConnectionManager.<init>(ConnectionManager.java:70)
[11:28:53] [WARNING]    at org.dragonet.raknet.client.JRakLibClient.run(JRakLibClient.java:218)**
[11:28:58] [INFO] Client MrSN[/192.168.0.6:19132] disconnected! Reason: Client disconnect`
