### ISSUE TITLE
No player is visible for the MCPE Client

### ISSUE THREAD

**Issue by MrPowerGamerBR** [DragonetMC/DragonProxy#63]

**Comment by MrPowerGamerBR** [comment]
```
`14:03:02 [ADVERT╩NCIA] java.lang.ClassCastException: java.lang.Integer cannot be
 cast to java.lang.Byte
14:03:02 [ADVERT╩NCIA]  at org.dragonet.proxy.network.translator.EntityMetaTrans
lator.translateToPE(EntityMetaTranslator.java:50)
14:03:02 [ADVERT╩NCIA]  at org.dragonet.proxy.network.translator.pc.PCSpawnPlaye
rPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:51)
14:03:02 [ADVERT╩NCIA]  at org.dragonet.proxy.network.translator.pc.PCSpawnPlaye
rPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:14)
14:03:02 [ADVERT╩NCIA]  at org.dragonet.proxy.network.PacketTranslatorRegister.t
ranslateToPE(PacketTranslatorRegister.java:133)
14:03:02 [ADVERT╩NCIA]  at org.dragonet.proxy.network.DownstreamSession$1.packet
Received(DownstreamSession.java:100)
14:03:02 [ADVERT╩NCIA]  at org.spacehq.packetlib.event.session.PacketReceivedEve
nt.call(PacketReceivedEvent.java:50)
14:03:02 [ADVERT╩NCIA]  at org.spacehq.packetlib.tcp.TcpSession.callEvent(TcpSes
sion.java:131)
14:03:02 [ADVERT╩NCIA]  at org.spacehq.packetlib.tcp.TcpSession$3.run(TcpSession
.java:324)
14:03:02 [ADVERT╩NCIA]  at java.lang.Thread.run(Unknown Source)
```

**Comment by DefinitlyEvil** [comment]
Try out 0.0.2, I've fixed that entity meta translation error.

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil still isn't working :cry:

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR Weird xD Checkout `EntityMetaTransator` and there must be a illegal cast.

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil 
2016/01/18 08:16:16 [WARNING] java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
2016/01/18 08:16:16 [WARNING] 	at org.dragonet.proxy.network.translator.EntityMetaTranslator.translateToPE(EntityMetaTranslator.java:50)
2016/01/18 08:16:16 [WARNING] 	at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:51)
2016/01/18 08:16:16 [WARNING] 	at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:14)
2016/01/18 08:16:16 [WARNING] 	at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:133)
2016/01/18 08:16:16 [WARNING] 	at org.dragonet.proxy.network.DownstreamSession$1.packetReceived(DownstreamSession.java:100)
2016/01/18 08:16:16 [WARNING] 	at org.spacehq.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:50)
2016/01/18 08:16:16 [WARNING] 	at org.spacehq.packetlib.tcp.TcpSession.callEvent(TcpSession.java:131)
2016/01/18 08:16:16 [WARNING] 	at org.spacehq.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
2016/01/18 08:16:16 [WARNING] 	at java.lang.Thread.run(Thread.java:745)

**Comment by MrPowerGamerBR** [comment]
I will test the last build, if it is fixed, I will close the issue.

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil 

```
10:31:58 [WARNING] java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Integer
10:31:58 [WARNING]      at org.dragonet.proxy.network.translator.EntityMetaTranslator.translateToPE(EntityMetaTranslator.java:50)
10:31:58 [WARNING]      at org.dragonet.proxy.network.translator.pc.PCSpawnMobPacketTranslator.translate(PCSpawnMobPacketTranslator.java:45)
10:31:58 [WARNING]      at org.dragonet.proxy.network.translator.pc.PCSpawnMobPacketTranslator.translate(PCSpawnMobPacketTranslator.java:25)
10:31:58 [WARNING]      at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:133)
10:31:58 [WARNING]      at org.dragonet.proxy.network.DownstreamSession$1.packetReceived(DownstreamSession.java:100)
10:31:58 [WARNING]      at org.spacehq.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:50)
10:31:58 [WARNING]      at org.spacehq.packetlib.tcp.TcpSession.callEvent(TcpSession.java:131)
10:31:58 [WARNING]      at org.spacehq.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
10:31:58 [WARNING]      at java.lang.Thread.run(Thread.java:745)
```

You will need to verify if the value is a Integer or a Byte.

```
if (m.getValue() instanceof Byte) {
// It is a byte
} else {
// It is a Integer
}
```

I don't know why the Server sends Bytes and sometimes sends Integers.

**Comment by DefinitlyEvil** [comment]
Maybe for different meanings, gonna check it out later.

**Comment by JuniorJPDJ** [comment]
still not working, players are not visible or sometimes visible as a fire (?!)
