### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by wangyw15** [DragonetMC/DragonProxy#66]
I have compile it by myself, and it's successful, but when I put it into plugin folder and start the server, it haven't been loaded.

Server: PaperSpigot 1.12.1
Version git-Paper-1190 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

Error info:
Could not load 'plugins\dragonproxy-0.0.6-preR1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.12.1.jar:git-Paper-1190]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [patched_1.12.1.jar:git-Paper-1190]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [patched_1.12.1.jar:git-Paper-1190]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) [patched_1.12.1.jar:git-Paper-1190]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.1.jar:git-Paper-1190]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more
![a](https://user-images.githubusercontent.com/18070676/31062091-8d190730-a75a-11e7-8303-54dd1a406350.png)

**Comment by wangyw15** [comment]
Emm... It can be ran directly...
