### ISSUE TITLE
Dragonet still not working

### ISSUE THREAD

**Issue by ogmkp** [DragonetMC/DragonProxy#90]
Hello.

Thank for your support for this project, i've compiled and run the master branch and the client still freezing when it attempt to connect to dragonet.
The machine who host Spigot 1.12.2 haven't any input from dragonet.

Do you have solution ?

Thanks for this dev staging project.

Runing Debian 9 with Java(TM) SE Runtime Environment (build 9.0.1+11)

>>  https://pastebin.com/muZ1EpPF

`modified: removed all the CRAP`

**Comment by ogmkp** [comment]
Same with this release:
https://github.com/DragonetMC/DragonProxy/releases/tag/0.2.1-preR1

Thank you.

**Comment by HoverEpic** [comment]
Java 9 not compatible.

**Comment by ogmkp** [comment]
I've tested with Java 8 and OpenJDK 8 from Debian too.

**Comment by HoverEpic** [comment]
It seems to be a netty issue with Java 9, have you tried on the same machine? Are you sure the Java 8 jvm is enabled?

**Comment by DefinitlyEvil** [comment]
`java -version`

**Comment by maxdrash** [comment]
Tested with Java 8, better things happen but still not working, there lot of java errors:
java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)


:~/DragonProxy/proxy/target$ java -jar dragonproxy-0.2.1-preR1.jar
[12:19:18] [WARNING] §eThis is a development build. It may contain bugs. Do not use on production.

[12:19:18] [INFO] Starting up DragonProxy, version: 0.2.1-preR1 ...
[12:19:18] [INFO] Supported version of Minecraft PC/Mac: 1.12.2
[12:19:18] [INFO] Supported version of Minecraft: Pocket/Windows 10 Edition: v1.2.5
[12:19:18] [INFO] Creating thread pool(Size:16)...
[12:19:18] [INFO] Binding on 0.0.0.0:19132 ...
[12:19:18] [INFO] The proxy has started!
PING /77.136.17.182:42313
PING /77.136.17.182:42313
CLIENT CONNECT
CLIENT PROTOCOL = 141
[12:19:18] [INFO] Player madxmaxxd[/77.136.17.182:53717] connected!
[12:19:18] [INFO] Bridge established for player madxmaxxd[/77.136.17.182:53717]!
Handler exception: readerIndex(20) + length(1) exceeds writerIndex(20): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 20, widx: 20, cap: 20)
java.lang.IndexOutOfBoundsException: readerIndex(20) + length(1) exceeds writerIndex(20): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 20, widx: 20, cap: 20)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1401)
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
        at net.marfgamer.jraknet.Packet.read(Packet.java:148)
        at net.marfgamer.jraknet.Packet.checkMagic(Packet.java:353)
        at net.marfgamer.jraknet.protocol.status.UnconnectedPing.decode(UnconnectedPing.java:69)
        at net.marfgamer.jraknet.server.RakNetServer.handleMessage(RakNetServer.java:564)
        at net.marfgamer.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:137)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IndexOutOfBoundsException: readerIndex(20) + length(1) exceeds writerIndex(20): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 20, widx: 20, cap: 20)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1401)
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
        at net.marfgamer.jraknet.Packet.read(Packet.java:148)
        at net.marfgamer.jraknet.Packet.checkMagic(Packet.java:353)
        at net.marfgamer.jraknet.protocol.status.UnconnectedPing.decode(UnconnectedPing.java:69)
        at net.marfgamer.jraknet.server.RakNetServer.handleMessage(RakNetServer.java:564)
        at net.marfgamer.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:137)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
CLIENT DISCONNECT
[12:19:18] [INFO] Client madxmaxxd[/77.136.17.182:53717] disconnected! Reason: Client disconnect
PING /77.136.17.182:42313
PING /77.136.17.182:42313
stop
stop
PING /77.136.17.182:42313
^C 


Spigot 1.12.2 side:

_>                                                                              
_[12:19:31 INFO]: com.mojang.authlib.GameProfile@4e72bd78[id=<null>,name=madxmaxxd,properties={},legacy=false] (/10.0.0.140:60286) lost connection: Disconnected_
>_  

Nothing else.

Thank you.

**Comment by DefinitlyEvil** [comment]
probably your RAM is tooooo low, try:
`java -Xmx1G -jar dragonproxy-x.x.x.jar`
you can adjust `1G` to something like `512M`

**Comment by ogmkp** [comment]
i have 4 Gb :

~/DragonProxy/proxy/target$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3,9G        211M        683M         19M        3,0G        3,4G
Swap:          2,0G          0B        2,0G

But trying with these parameters, nothing new:

https://pastebin.com/xgqsaSsY

I don't know where i've made a mistake.
Thank you.

**Comment by ogmkp** [comment]
in the future, i will join the debuging console by attached txt.

here the config:

[00_config.txt](https://github.com/DragonetMC/DragonProxy/files/1505925/00_config.txt)

Thank you.

**Comment by HoverEpic** [comment]
It's a weird  probleme, jraknet can't handle packets from the client... Can you try with nukkit server? Maybe a network issue.

**Comment by ogmkp** [comment]
Trying with nukkit as a target from DragonProxy or straight to nukkit ?

**Comment by DefinitlyEvil** [comment]
DragonProxy can NOT to Nukkit, you MUST target to a Minecraft: Java Edition server like CraftBukkit or Spigot. OMG YOU DIDN'T EVEN READ THE INTRODUCTION?

**Comment by DefinitlyEvil** [comment]
next time please use pastebin or sth or it will be locked

**Comment by ogmkp** [comment]
https://github.com/DragonetMC/DragonProxy/issues/90#issuecomment-347239247
It's for me ?

**Comment by HoverEpic** [comment]
I just wonder if a jraknet based server works with his machine, it just for testing if there is no error with nukkit core. No need to be hangry ^^

**Comment by ogmkp** [comment]
I do not understand your reaction. Why such anger ? You do not want us to help you to fix the bugs ?
Why have you edit and deleted my comments ?

**Comment by HoverEpic** [comment]
Let's continue testing. Have you tried to start a nukkit server on your host and connect derectly to it?
(connect to it directly, don't start dragon proxy, and see if there is errors.)

**Comment by ogmkp** [comment]
yes I did, there are no problems with nukkit.
i'm gonna setup a new host with debian 9, Oracle Java 8 and making new tests.

**Comment by HoverEpic** [comment]
I have no idea what cause this problem, I have tested the proxy on windows on local host only, and I cannot test it now.
(can you put your logs in spoilers or something to hide them, I have to scroll miles to reach the bottom on my mobile)

**Comment by ogmkp** [comment]
I set up a new machine under Debian 9 and Java 8, no improvement on DragonProxy side.
But, on Spigot, I've put the online-mode to false and now I can connect to the world but only for 1 second. 
Spigot reject the MCPE client 1 second after it start to load some chunks and no more.

DragonProxy side: https://pastebin.com/sYEaVhvb
Spigot side: https://pastebin.com/fRFmXJ8k

Thanks for you help.

**Comment by HoverEpic** [comment]
I think you should consider it's not ready for use for now... Sorry but I think I couldn't help more.
Ill take a look about systems compatibilités in 2 weeks.

**Comment by ogmkp** [comment]
ok thanks anyway ^^

**Comment by DefinitlyEvil** [comment]
Well it seemed not our issue so...
